// src/pages/hse/hseSopData.js
// HSE Standard Operating Procedures — full bilingual (EN / AR) document set.
// Structure mirrors the HACCP/ISO SOP model (sections-based) so the HSE SOP page
// can render the same card + full-screen modal experience.
//
// Each SOP:
//   { id, code, number, title, titleAr, subtitle, subtitleAr,
//     docNo, facility, facilityAr, preparedBy, issueDate, revision,
//     group, category, categoryAr,
//     sections: [{ heading, headingAr, content, contentAr }] }
//
// Groups: fs (Food Safety & Cold Chain), ohs (Occupational Health & Safety),
//         em (Emergency), en (Environment), ad (Administrative).

export const SOP_GROUP_META = {
  fs:  { key: "fs",  label: "Food Safety & Cold Chain", labelAr: "سلامة الغذاء وسلسلة التبريد", color: "#0369a1", accent: "sky" },
  ohs: { key: "ohs", label: "Occupational Health & Safety", labelAr: "السلامة المهنية", color: "#9a3412", accent: "orange" },
  em:  { key: "em",  label: "Emergency", labelAr: "الطوارئ", color: "#b91c1c", accent: "red" },
  en:  { key: "en",  label: "Environment", labelAr: "البيئة", color: "#15803d", accent: "green" },
  ad:  { key: "ad",  label: "Administrative", labelAr: "الإدارية المساندة", color: "#7c3aed", accent: "purple" },
};

// Category colour palette keyed by group — used for card / modal badges.
export const groupColors = {
  fs:  { bg: "rgba(3,105,161,0.12)",  border: "rgba(3,105,161,0.38)",  text: "#0369a1" },
  ohs: { bg: "rgba(234,88,12,0.12)",  border: "rgba(234,88,12,0.38)",  text: "#9a3412" },
  em:  { bg: "rgba(220,38,38,0.12)",  border: "rgba(220,38,38,0.38)",  text: "#b91c1c" },
  en:  { bg: "rgba(22,163,74,0.12)",  border: "rgba(22,163,74,0.38)",  text: "#15803d" },
  ad:  { bg: "rgba(124,58,237,0.12)", border: "rgba(124,58,237,0.38)", text: "#7c3aed" },
};

const COMMON = {
  facility: "Al Mawashi — Meat Import, Cold Storage & Distribution",
  facilityAr: "المواشي — استيراد اللحوم والتخزين المبرّد والتوزيع",
  preparedBy: "HSE",
  issueDate: "01/01/2026",
  revision: "01",
};

// Small helper to keep each SOP definition compact.
function sop(g, n, o) {
  const code = `SOP-${g.toUpperCase()}-${String(n).padStart(2, "0")}`;
  return {
    id: code.toLowerCase(),
    code,
    number: code,
    group: g,
    category: SOP_GROUP_META[g].label,
    categoryAr: SOP_GROUP_META[g].labelAr,
    docNo: `HSE-SOP/${g.toUpperCase()}/${String(n).padStart(2, "0")}`,
    ...COMMON,
    ...o,
  };
}

const S = (heading, headingAr, content, contentAr) => ({ heading, headingAr, content, contentAr });

export const hseSops = [
  // ══════════════════════════════════════════════════════════════════════
  // FOOD SAFETY & COLD CHAIN
  // ══════════════════════════════════════════════════════════════════════
  sop("fs", 1, {
    title: "Receiving Imported Shipments",
    titleAr: "استلام الشحنات المستوردة",
    subtitle: "Temperature, health/Halal certificates & conformity at receipt (critical CCP)",
    subtitleAr: "فحص الحرارة والشهادات الصحية والحلال والمطابقة عند الاستلام (نقطة تحكم حرجة)",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Ensure every meat shipment arriving by air or sea conforms to specifications before acceptance and storage, preventing the introduction of food-safety hazards into the cold chain.",
        "ضمان أن كل شحنة لحوم تصل جوّاً أو بحراً مطابقة للمواصفات قبل قبولها وتخزينها، لمنع إدخال مخاطر سلامة الغذاء إلى سلسلة التبريد."),
      S("2. Scope", "٢. النطاق",
        "All imported shipments — from the receipt point (Cargo Village / Jebel Ali) to placement in chiller/freezer rooms.",
        "كل الشحنات المستوردة — من نقطة الاستلام (Cargo Village / جبل علي) حتى الإيداع في غرف التبريد/التجميد."),
      S("3. Responsibilities", "٣. المسؤوليات",
        "• Receiving Officer / QA: perform inspection, temperature readings and the accept/reject decision.\n• Food Safety Officer: verify certificates and authorise quarantine/rejection.\n• Store Keeper: place accepted stock in the correct room and record batch/location.\n• HSE Manager: review deviations and trends.",
        "• مسؤول الاستلام/الجودة: تنفيذ الفحص وقراءات الحرارة وقرار القبول/الرفض.\n• مسؤول سلامة الغذاء: التحقق من الشهادات واعتماد الحجر/الرفض.\n• أمين المستودع: إيداع البضاعة المقبولة في الغرفة الصحيحة وتسجيل الدفعة/الموقع.\n• مدير HSE: مراجعة الانحرافات والاتجاهات."),
      S("4. Procedure", "٤. الإجراء",
        "1) Visual inspection of the truck and refrigerated container.\n2) Measure truck temperature + product core + surface (3 readings).\n3) Verify veterinary health certificate, Halal certificate and Country of Origin (COO).\n4) Visual check of packaging, odour and any contamination.\n5) Decision: accept / reject / partial accept / quarantine.\n6) Record in receiving form F-09.\n7) Place in the appropriate chiller/freezer room.",
        "١) فحص بصري للشاحنة وحاوية التبريد.\n٢) قياس حرارة الشاحنة + قلب المنتج + سطحه (٣ قراءات).\n٣) التحقق من الشهادة الصحية البيطرية وشهادة الحلال وبلد المنشأ (COO).\n٤) فحص بصري للتغليف والرائحة وأي تلوث.\n٥) القرار: قبول / رفض / قبول جزئي / حجر صحي.\n٦) التسجيل في نموذج الاستلام F-09.\n٧) الإيداع في غرفة التبريد/التجميد المناسبة."),
      S("5. Acceptance Criteria", "٥. معايير القبول",
        "• Chilled core ≤ +4 °C; frozen core ≤ -18 °C.\n• Valid veterinary + Halal certificates matching the consignment.\n• Intact packaging, no off-odour, no visible contamination or thawing/refreezing signs.",
        "• قلب المنتج المبرّد ≤ +٤°م؛ المجمّد ≤ -١٨°م.\n• شهادات بيطرية + حلال سارية ومطابقة للإرسالية.\n• تغليف سليم، لا روائح غريبة، لا تلوث ظاهر أو علامات ذوبان/إعادة تجميد."),
      S("6. Records", "٦. السجلات",
        "F-09 (Shipment Receiving Log), certificate copies, shipment photos at receipt, temperature readings.",
        "F-09 (سجل استلام الشحنات)، نسخ الشهادات، صور الشحنة عند الاستلام، قراءات الحرارة."),
      S("7. Frequency", "٧. التكرار",
        "On every shipment — critical control point (CCP).",
        "عند كل شحنة — نقطة تحكم حرجة (CCP)."),
    ],
  }),
  sop("fs", 2, {
    title: "Temperature Monitoring & Calibration",
    titleAr: "مراقبة ومعايرة درجات الحرارة",
    subtitle: "Chiller & freezer rooms, dispatch areas and transport — every 4 hours, 24/7",
    subtitleAr: "غرف التبريد والتجميد ومناطق الشحن والنقل — كل ٤ ساعات على مدار الساعة",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Maintain the cold chain within target limits and log readings in a documented way to meet HACCP and Dubai Municipality requirements.",
        "الحفاظ على سلسلة التبريد ضمن الحدود المستهدفة وتسجيل القراءات بشكل موثّق لتلبية متطلبات HACCP وبلدية دبي."),
      S("2. Scope", "٢. النطاق",
        "All chiller (0 to +4 °C) and freezer (-18 °C) rooms, receiving and dispatch areas, and refrigerated transport trucks.",
        "كل غرف التبريد (٠ إلى +٤°م) والتجميد (-١٨°م)، ومناطق الاستلام والشحن، وشاحنات النقل المبرّدة."),
      S("3. Responsibilities", "٣. المسؤوليات",
        "• Store / Cold-chain staff: take and log readings on schedule.\n• Maintenance: respond to alarms and equipment faults.\n• QA: audit logs, manage calibration, cross-check data loggers.",
        "• طاقم المستودع/سلسلة التبريد: أخذ وتسجيل القراءات حسب الجدول.\n• الصيانة: الاستجابة للإنذارات وأعطال المعدات.\n• الجودة: تدقيق السجلات وإدارة المعايرة ومطابقة أجهزة التسجيل."),
      S("4. Procedure", "٤. الإجراء",
        "1) Read temperatures every 4 hours in each room.\n2) Log the reading in form F-08.\n3) On deviation > 2 °C → trigger SOP-FS-03.\n4) Calibrate measuring devices every 6 months at an accredited lab.\n5) Check data loggers daily.\n6) Cross-check manual vs data-logger readings weekly.",
        "١) قياس الحرارة كل ٤ ساعات في كل غرفة.\n٢) تسجيل القراءة في نموذج F-08.\n٣) عند انحراف > ٢°م ← تفعيل SOP-FS-03.\n٤) معايرة أجهزة القياس كل ٦ أشهر في مختبر معتمد.\n٥) فحص أجهزة التسجيل يومياً.\n٦) مطابقة القراءات اليدوية مع أجهزة التسجيل أسبوعياً."),
      S("5. Records", "٥. السجلات",
        "F-08 (Temperature Log), calibration certificates, data-logger reports.",
        "F-08 (سجل درجات الحرارة)، شهادات المعايرة، تقارير أجهزة التسجيل."),
      S("6. Frequency", "٦. التكرار",
        "Every 4 hours (24/7); calibration every 6 months; data-logger check daily.",
        "كل ٤ ساعات (٢٤/٧)؛ المعايرة كل ٦ أشهر؛ فحص أجهزة التسجيل يومياً."),
    ],
  }),
  sop("fs", 3, {
    title: "Temperature Deviation Response",
    titleAr: "التعامل مع انحرافات درجة الحرارة",
    subtitle: "Triggers, escalation, product hold / release decision",
    subtitleAr: "المحفزات والتصعيد وقرار حجز/الإفراج عن المنتج",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Respond immediately to any cold-chain temperature deviation to prevent product spoilage and assess safety before release.",
        "الاستجابة الفورية لأي انحراف في حرارة سلسلة التبريد لمنع فساد المنتج وتقييم سلامته قبل الإفراج عنه."),
      S("2. Scope", "٢. النطاق",
        "Any deviation exceeding the allowed limit (> +4 °C chilled, > -15 °C frozen) for more than 30 minutes.",
        "كل انحراف يتجاوز الحد المسموح (> +٤°م تبريد، > -١٥°م تجميد) لأكثر من ٣٠ دقيقة."),
      S("3. Procedure", "٣. الإجراء",
        "1) Immediate alarm + notify the Food Safety Officer.\n2) Hold the affected product.\n3) Assess severity and duration of the deviation.\n4) Measure product core temperature.\n5) Decision: release / re-process / destroy.\n6) Root-cause investigation.\n7) Corrective action and effectiveness check.",
        "١) إنذار فوري + إبلاغ مسؤول سلامة الغذاء.\n٢) عزل المنتج المتأثر (Hold).\n٣) تقييم شدة الانحراف ومدته.\n٤) قياس حرارة قلب المنتج.\n٥) القرار: إفراج / إعادة معالجة / إتلاف.\n٦) التحقيق في السبب الجذري.\n٧) إجراء تصحيحي والتحقق من فعاليته."),
      S("4. Records", "٤. السجلات",
        "Deviation report, release/destroy decision, CAPA (F-20).",
        "تقرير الانحراف، قرار الإفراج/الإتلاف، الإجراء التصحيحي CAPA (F-20)."),
      S("5. Frequency", "٥. التكرار",
        "On every deviation.",
        "عند كل انحراف."),
    ],
  }),
  sop("fs", 4, {
    title: "Cleaning & Sanitation Procedure",
    titleAr: "إجراء التنظيف والتعقيم",
    subtitle: "Daily / weekly / monthly deep-clean of line, rooms, tools & facilities",
    subtitleAr: "تنظيف يومي/أسبوعي/شهري عميق للخط والغرف والأدوات والمرافق",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Maintain a production environment free of pathogenic bacteria and physical/chemical contaminants.",
        "الحفاظ على بيئة إنتاج خالية من البكتيريا الممرضة والملوثات الفيزيائية والكيميائية."),
      S("2. Scope", "٢. النطاق",
        "Processing line, cold rooms, tools and equipment, floors, hand-wash sinks, and toilets.",
        "خط التصنيع، الغرف الباردة، الأدوات والمعدات، الأرضيات، أحواض غسل اليدين، دورات المياه."),
      S("3. Procedure", "٣. الإجراء",
        "1) Remove gross debris.\n2) Rinse with water.\n3) Apply detergent.\n4) Mechanical scrubbing.\n5) Rinse.\n6) Apply sanitizer at the correct concentration.\n7) Allow the contact time.\n8) Final rinse.\n9) Visual + ATP verification.\n10) Log in F-10.",
        "١) إزالة المخلفات الخشنة.\n٢) الشطف بالماء.\n٣) تطبيق المنظف.\n٤) فرك ميكانيكي.\n٥) الشطف.\n٦) تطبيق المعقّم بالتركيز الصحيح.\n٧) ترك زمن التلامس.\n٨) شطف نهائي.\n٩) تحقق بصري + ATP.\n١٠) التسجيل في F-10."),
      S("4. Records", "٤. السجلات",
        "F-10 (Cleaning Log), sanitizer concentration certificates, ATP results.",
        "F-10 (سجل التنظيف)، شهادات تركيز المعقّمات، نتائج ATP."),
      S("5. Frequency", "٥. التكرار",
        "Daily + weekly + monthly deep clean.",
        "يومي + أسبوعي + شهري عميق."),
    ],
  }),
  sop("fs", 5, {
    title: "Microbiological Swabbing Program",
    titleAr: "برنامج المسحات الميكروبية",
    subtitle: "Surface + hand swabs and accredited-lab verification of hygiene",
    subtitleAr: "مسحات الأسطح والأيدي والتحقق المخبري المعتمد من فعالية النظافة",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Scientifically verify the effectiveness of the cleaning/sanitation program and detect any microbial contamination early.",
        "التحقق العلمي من فعالية برنامج التنظيف والتعقيم وكشف أي تلوث ميكروبي مبكراً."),
      S("2. Scope", "٢. النطاق",
        "Food-contact surfaces, workers' hands, cutting tools, floors, and rinse water.",
        "أسطح التلامس مع الغذاء، أيدي العاملين، أدوات التقطيع، الأرضيات، مياه الشطف."),
      S("3. Procedure", "٣. الإجراء",
        "1) Monthly plan defining points and test types.\n2) Take swabs with sterile tools.\n3) Send to an accredited lab.\n4) Analyse results against allowed limits.\n5) On failure: immediate re-sanitation + re-test + investigation.\n6) Monthly trend monitoring.",
        "١) خطة شهرية تحدّد النقاط ونوع الفحص.\n٢) أخذ المسحات بأدوات معقّمة.\n٣) الإرسال لمختبر معتمد.\n٤) تحليل النتائج وفق الحدود المسموحة.\n٥) عند الفشل: تعقيم فوري + إعادة فحص + تحقيق.\n٦) رصد الاتجاهات شهرياً."),
      S("4. Records", "٤. السجلات",
        "F-11 (Swabs Log), lab reports, monthly trend reports.",
        "F-11 (سجل المسحات)، تقارير المختبر، تقارير الاتجاه الشهرية."),
      S("5. Frequency", "٥. التكرار",
        "Weekly for critical surfaces, monthly for other samples.",
        "أسبوعي للأسطح الحرجة، شهري للعينات الأخرى."),
    ],
  }),
  sop("fs", 6, {
    title: "Product Recall Procedure",
    titleAr: "إجراء استرجاع المنتج من السوق",
    subtitle: "Backward + forward trace, retrieval, destruction & regulator notification",
    subtitleAr: "تتبّع عكسي وأمامي واسترجاع وإتلاف وإخطار الجهات الرقابية",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Rapidly recall any unsafe product from the market to protect the consumer, the company's reputation, and to meet regulatory requirements.",
        "الاستجابة السريعة لسحب أي منتج غير آمن من السوق لحماية المستهلك وسمعة الشركة وتلبية متطلبات الجهات الرقابية."),
      S("2. Scope", "٢. النطاق",
        "Any product that has left the company gate and is later identified as unsafe (test result, complaint, deviation, external news).",
        "أي منتج غادر بوابة الشركة وتبيّن لاحقاً عدم سلامته (نتيجة فحص، شكوى، انحراف، خبر خارجي)."),
      S("3. Procedure", "٣. الإجراء",
        "1) Form an emergency recall team.\n2) Identify the batch and quantity.\n3) Trace all customers who received it.\n4) Notify the municipality and retrieve goods.\n5) Confirm receipt from each customer.\n6) Documented destruction.\n7) Investigation + root cause.\n8) Final report to management and municipality.",
        "١) تشكيل فريق استرجاع طارئ.\n٢) تحديد دفعة المنتج وكميته.\n٣) تتبّع كل العملاء الذين استلموا.\n٤) إخطار البلدية وسحب البضاعة.\n٥) تأكيد الاستلام من كل عميل.\n٦) إتلاف موثّق.\n٧) تحقيق وسبب جذري.\n٨) تقرير نهائي للإدارة والبلدية."),
      S("4. Records", "٤. السجلات",
        "Mock recall form, traceability log, destruction certificates, final report.",
        "نموذج التجربة الوهمية، سجل التتبّع، شهادات الإتلاف، التقرير النهائي."),
      S("5. Frequency", "٥. التكرار",
        "When needed + quarterly mock drill.",
        "عند الحاجة + تجربة وهمية ربع سنوية."),
    ],
  }),
  sop("fs", 7, {
    title: "Product Traceability",
    titleAr: "التتبّع العكسي والأمامي للمنتجات",
    subtitle: "One-hour trace from original supplier to final customer and back",
    subtitleAr: "تتبّع خلال ساعة من المورّد الأصلي إلى العميل النهائي والعكس",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Enable tracing of any meat piece in less than one hour, from the original supplier to the final customer and vice-versa.",
        "إمكانية تتبّع أي قطعة لحم في أقل من ساعة من المورّد الأصلي إلى العميل النهائي والعكس."),
      S("2. Scope", "٢. النطاق",
        "All products from receipt until final delivery, including products processed on the production line.",
        "كل المنتجات من لحظة الاستلام حتى التسليم النهائي، شامل المنتجات المُجهّزة في خط التصنيع."),
      S("3. Procedure", "٣. الإجراء",
        "1) Log the batch number at receipt.\n2) Link batches to storage location.\n3) Record internal transfers.\n4) Link the batch to the customer at dispatch.\n5) Monthly traceability test (random sample).",
        "١) تسجيل رقم الدفعة عند الاستلام.\n٢) ربط الدفعات بمكان التخزين.\n٣) تسجيل التحويلات الداخلية.\n٤) ربط الدفعة بالعميل عند الشحن.\n٥) اختبار تتبّع شهري (عينة عشوائية)."),
      S("4. Records", "٤. السجلات",
        "Digital traceability system, in/out logs, monthly test reports.",
        "نظام تتبّع رقمي، سجلات الدخول والخروج، تقارير الاختبار الشهري."),
      S("5. Frequency", "٥. التكرار",
        "Continuous + monthly test.",
        "مستمر + اختبار شهري."),
    ],
  }),
  sop("fs", 8, {
    title: "Halal / Non-Halal Segregation",
    titleAr: "فصل اللحوم الحلال وغير الحلال",
    subtitle: "Certified Halal-only facility, dedicated tools & annual Halal audit",
    subtitleAr: "منشأة حلال معتمدة فقط، أدوات مخصصة وتدقيق حلال سنوي",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Ensure no mixing of Halal meat with any non-Halal source at any operational stage, fulfilling mandatory ESMA and UAE.S 2055-1 requirements.",
        "ضمان عدم اختلاط اللحوم الحلال بأي مصدر غير حلال في أي مرحلة تشغيلية، تلبيةً للمتطلبات الإلزامية لـ ESMA و UAE.S 2055-1."),
      S("2. Scope", "٢. النطاق",
        "All stages: receipt, storage, processing, packaging and distribution.",
        "كل المراحل: الاستلام، التخزين، التصنيع، التغليف، التوزيع."),
      S("3. Procedure", "٣. الإجراء",
        "1) All imported meat carries a certified Halal certificate.\n2) No non-Halal products in the facility.\n3) Dedicated tools and apparel.\n4) Annual external Halal audit.\n5) Worker training on Halal requirements.",
        "١) كل اللحوم المستوردة بشهادة حلال معتمدة.\n٢) لا منتجات غير حلال في المنشأة.\n٣) أدوات وملابس مخصّصة.\n٤) تدقيق حلال خارجي سنوي.\n٥) تدريب العاملين على المتطلبات الشرعية."),
      S("4. Records", "٤. السجلات",
        "Halal certificates, annual audit reports, training records.",
        "شهادات الحلال، تقارير التدقيق السنوي، سجلات التدريب."),
      S("5. Frequency", "٥. التكرار",
        "Continuous + annual audit.",
        "مستمر + تدقيق سنوي."),
    ],
  }),
  sop("fs", 9, {
    title: "Expiry / Shelf-Life Management",
    titleAr: "إدارة المنتجات منتهية أو قريبة الانتهاء",
    subtitle: "FIFO / FEFO stock rotation with 60-day early-warning system",
    subtitleAr: "تدوير المخزون FIFO/FEFO مع نظام تنبيه مبكر قبل ٦٠ يوماً",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Prevent expired products from being in stock or market, and minimise losses through FIFO/FEFO inventory management.",
        "منع تواجد منتجات منتهية الصلاحية في المخزون أو السوق، وتقليل الخسائر عبر إدارة المخزون بنظام FIFO/FEFO."),
      S("2. Scope", "٢. النطاق",
        "All products in chillers, freezers and finished-product stores.",
        "كل المنتجات في غرف التبريد والتجميد ومخازن المنتج النهائي."),
      S("3. Procedure", "٣. الإجراء",
        "1) Apply FIFO (oldest out first) for younger stock.\n2) Apply FEFO (closest expiry out first) for varied dates.\n3) Auto-alert 60 days before expiry.\n4) Notify sales for promotional pricing.\n5) Documented destruction of expired stock.\n6) Update inventory.",
        "١) تطبيق FIFO (الأقدم يخرج أولاً) للمخزون الأحدث.\n٢) تطبيق FEFO (الأقرب انتهاءً يخرج أولاً) للتواريخ المتفاوتة.\n٣) تنبيه آلي قبل الانتهاء بـ ٦٠ يوماً.\n٤) إخطار المبيعات للتسعير الترويجي.\n٥) إتلاف موثّق للمنتهي.\n٦) تحديث المخزون."),
      S("4. Records", "٤. السجلات",
        "Inventory reports, destruction log, system alerts.",
        "تقارير المخزون، سجل الإتلاف، تنبيهات النظام."),
      S("5. Frequency", "٥. التكرار",
        "Daily + weekly management report.",
        "يومي + تقرير أسبوعي للإدارة."),
    ],
  }),

  // ══════════════════════════════════════════════════════════════════════
  // OCCUPATIONAL HEALTH & SAFETY
  // ══════════════════════════════════════════════════════════════════════
  sop("ohs", 1, {
    title: "New Employee HSE Induction",
    titleAr: "التدريب التعريفي للموظفين الجدد",
    subtitle: "Day-1 onboarding on hazards, PPE, emergency and hygiene rules",
    subtitleAr: "تدريب اليوم الأول على المخاطر ومعدات الوقاية والطوارئ وقواعد النظافة",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Ensure every new employee understands site hazards, safe work rules, emergency procedures and hygiene requirements before starting work.",
        "ضمان فهم كل موظف جديد لمخاطر الموقع وقواعد العمل الآمن وإجراءات الطوارئ ومتطلبات النظافة قبل بدء العمل."),
      S("2. Scope", "٢. النطاق",
        "All new employees, transfers, contractors and long-term visitors before their first working shift.",
        "كل الموظفين الجدد والمنقولين والمقاولين والزوار طويلي الأمد قبل أول وردية عمل."),
      S("3. Procedure", "٣. الإجراء",
        "1) HR schedules induction on the first day — no floor access before completion.\n2) Cover: site hazards, cold rooms, PPE, manual handling, emergency exits & assembly point, incident reporting, hygiene.\n3) Site walk-through of exits, extinguishers, first-aid points and assembly area.\n4) Assess understanding (short quiz / verbal check).\n5) Employee signs the induction record; issue PPE.\n6) Assign a buddy/supervisor for the first week.",
        "١) الموارد البشرية تجدول التعريف في اليوم الأول — لا دخول للصالة قبل إتمامه.\n٢) تغطية: مخاطر الموقع، الغرف الباردة، معدات الوقاية، المناولة اليدوية، مخارج الطوارئ ونقطة التجمّع، الإبلاغ عن الحوادث، النظافة.\n٣) جولة ميدانية على المخارج والطفايات ونقاط الإسعاف ومنطقة التجمّع.\n٤) تقييم الفهم (اختبار قصير / تحقق شفهي).\n٥) توقيع الموظف على سجل التعريف؛ صرف معدات الوقاية.\n٦) تعيين مرافق/مشرف خلال الأسبوع الأول."),
      S("4. Records", "٤. السجلات",
        "Signed induction checklist, PPE issue record, induction quiz result, training matrix update.",
        "قائمة التعريف الموقّعة، سجل صرف معدات الوقاية، نتيجة اختبار التعريف، تحديث مصفوفة التدريب."),
      S("5. Frequency", "٥. التكرار",
        "On hire / transfer, before first shift; refresher on major changes.",
        "عند التعيين/النقل قبل أول وردية؛ تحديث عند أي تغيير جوهري."),
    ],
  }),
  sop("ohs", 2, {
    title: "Personal Protective Equipment (PPE) Usage",
    titleAr: "استخدام معدات الوقاية الشخصية",
    subtitle: "Area-specific PPE matrix, inspection, issue and replacement",
    subtitleAr: "مصفوفة معدات وقاية لكل منطقة مع الفحص والصرف والاستبدال",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Protect workers from cold, cuts, slips, chemical and other hazards by defining, issuing and enforcing the correct PPE per area.",
        "حماية العاملين من البرودة والقطوع والانزلاق والمواد الكيميائية وغيرها عبر تحديد وصرف وإلزام معدات الوقاية الصحيحة لكل منطقة."),
      S("2. Scope", "٢. النطاق",
        "All employees, contractors and visitors in production, cold rooms, receiving, dispatch and maintenance areas.",
        "كل الموظفين والمقاولين والزوار في الإنتاج والغرف الباردة والاستلام والشحن والصيانة."),
      S("3. PPE Matrix", "٣. مصفوفة معدات الوقاية",
        "• Production / cutting: cut-resistant gloves, apron, hairnet, safety shoes.\n• Freezer / chiller: insulated cold-store jacket, gloves, non-slip footwear.\n• Chemical / cleaning: chemical-resistant gloves, goggles, apron.\n• Forklift / loading: high-visibility vest, safety shoes.\n• Visitors: coat, hairnet, shoe covers.",
        "• الإنتاج/التقطيع: قفازات مقاومة للقطع، مريلة، شبكة شعر، أحذية سلامة.\n• التجميد/التبريد: جاكيت معزول للتخزين البارد، قفازات، أحذية مانعة للانزلاق.\n• المواد الكيميائية/التنظيف: قفازات مقاومة للكيماويات، نظارات واقية، مريلة.\n• الرافعات/التحميل: سترة عالية الوضوح، أحذية سلامة.\n• الزوار: معطف، شبكة شعر، أغطية أحذية."),
      S("4. Procedure", "٤. الإجراء",
        "1) Issue correct PPE on hire and on area change.\n2) Inspect PPE before each shift — damaged PPE is replaced immediately.\n3) Supervisors enforce PPE at entry; non-compliance = removal until corrected.\n4) Store PPE clean and dry; separate food-area PPE from other uses.\n5) Track issue and replacement in the PPE register.",
        "١) صرف معدات الوقاية الصحيحة عند التعيين وعند تغيير المنطقة.\n٢) فحص معدات الوقاية قبل كل وردية — يُستبدل التالف فوراً.\n٣) المشرفون يلزمون بالمعدات عند الدخول؛ المخالفة = إخراج حتى التصحيح.\n٤) تخزين المعدات نظيفة وجافة؛ فصل معدات منطقة الغذاء عن غيرها.\n٥) تتبّع الصرف والاستبدال في سجل معدات الوقاية."),
      S("5. Records", "٥. السجلات",
        "PPE issue register, pre-shift inspection log, replacement records.",
        "سجل صرف معدات الوقاية، سجل الفحص قبل الوردية، سجلات الاستبدال."),
      S("6. Frequency", "٦. التكرار",
        "Every shift (inspection); on issue / replacement as needed.",
        "كل وردية (الفحص)؛ عند الصرف/الاستبدال حسب الحاجة."),
    ],
  }),
  sop("ohs", 3, {
    title: "Safe Work in Frozen / Cold Rooms",
    titleAr: "العمل الآمن في الغرف المجمدة",
    subtitle: "Exposure limits, insulated PPE, buddy system & internal-release safety",
    subtitleAr: "حدود التعرّض، معدات معزولة، نظام المرافق، وأمان الفتح من الداخل",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Protect workers from cold stress, hypothermia and entrapment when working in freezer (-18 °C) and chiller rooms.",
        "حماية العاملين من إجهاد البرد وانخفاض الحرارة والاحتجاز عند العمل في غرف التجميد (-١٨°م) والتبريد."),
      S("2. Scope", "٢. النطاق",
        "All work inside chiller and freezer rooms, including loading, picking, cleaning and maintenance.",
        "كل الأعمال داخل غرف التبريد والتجميد، شامل التحميل والتجهيز والتنظيف والصيانة."),
      S("3. Procedure", "٣. الإجراء",
        "1) Wear insulated cold-store PPE (jacket, gloves, headwear, non-slip footwear).\n2) Limit continuous exposure and take scheduled warm-up breaks.\n3) Use the buddy system for extended tasks; never work alone in a freezer.\n4) Verify the internal safety release (door can always be opened from inside) and internal alarm before entry.\n5) Keep floors clear of ice build-up; report slip hazards.\n6) Know the emergency exit and alarm location.",
        "١) ارتداء معدات وقاية معزولة للتخزين البارد (جاكيت، قفازات، غطاء رأس، أحذية مانعة للانزلاق).\n٢) تحديد مدة التعرّض المستمر وأخذ فترات تدفئة مجدولة.\n٣) استخدام نظام المرافق للمهام الطويلة؛ لا عمل منفرد في غرفة التجميد.\n٤) التحقق من مفتاح الأمان الداخلي (يمكن فتح الباب دائماً من الداخل) والإنذار الداخلي قبل الدخول.\n٥) إبقاء الأرضيات خالية من تراكم الجليد؛ الإبلاغ عن مخاطر الانزلاق.\n٦) معرفة مخرج الطوارئ وموقع الإنذار."),
      S("4. Records", "٤. السجلات",
        "Cold-room entry / buddy log, internal-release inspection log, exposure-break schedule.",
        "سجل الدخول/المرافقة للغرف الباردة، سجل فحص مفتاح الأمان الداخلي، جدول فترات التعرّض."),
      S("5. Frequency", "٥. التكرار",
        "Every entry; internal-release check monthly.",
        "عند كل دخول؛ فحص مفتاح الأمان الداخلي شهرياً."),
    ],
  }),
  sop("ohs", 4, {
    title: "Forklift & Pallet-Truck Operation",
    titleAr: "تشغيل الرافعات الشوكية",
    subtitle: "Licensed operators, daily pre-use check, speed & pedestrian control",
    subtitleAr: "مشغّلون مرخّصون، فحص يومي قبل الاستخدام، وضبط السرعة والمشاة",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Prevent collisions, tip-overs and pedestrian injuries during forklift and powered pallet-truck operation.",
        "منع الاصطدامات والانقلاب وإصابات المشاة أثناء تشغيل الرافعات الشوكية وعربات البليت الكهربائية."),
      S("2. Scope", "٢. النطاق",
        "All powered lifting trucks and their operators in receiving, storage, dispatch and cold rooms.",
        "كل عربات الرفع الكهربائية ومشغّليها في الاستلام والتخزين والشحن والغرف الباردة."),
      S("3. Procedure", "٣. الإجراء",
        "1) Only trained and licensed operators may drive; verify licence validity.\n2) Daily pre-use check (brakes, horn, forks, tyres, hydraulics, warning light) logged before use.\n3) Observe site speed limit; sound horn at corners and doorways.\n4) Keep forks low when travelling; never lift people on the forks.\n5) Maintain pedestrian segregation and give way to pedestrians.\n6) Any defect = tag OUT OF SERVICE + maintenance request; park with forks down and brake engaged.",
        "١) لا يقود إلا مشغّلون مدرَّبون ومرخّصون؛ التحقق من صلاحية الرخصة.\n٢) فحص يومي قبل الاستخدام (الفرامل، البوق، الشوكات، الإطارات، الهيدروليك، ضوء التحذير) موثّق قبل التشغيل.\n٣) الالتزام بحد السرعة؛ استخدام البوق عند الزوايا والأبواب.\n٤) إبقاء الشوكات منخفضة أثناء السير؛ ممنوع رفع الأشخاص على الشوكات.\n٥) الحفاظ على فصل المشاة وإعطاؤهم الأولوية.\n٦) أي عطل = بطاقة \"خارج الخدمة\" + طلب صيانة؛ الركن بالشوكات لأسفل والفرامل مفعّلة."),
      S("4. Records", "٤. السجلات",
        "Operator licence register, daily pre-use checklist, defect / OUT OF SERVICE tags, maintenance records.",
        "سجل رخص المشغّلين، قائمة الفحص اليومي قبل الاستخدام، بطاقات الأعطال/\"خارج الخدمة\"، سجلات الصيانة."),
      S("5. Frequency", "٥. التكرار",
        "Daily pre-use check every shift; licence review annually; servicing per schedule.",
        "فحص يومي قبل الاستخدام كل وردية؛ مراجعة الرخص سنوياً؛ الصيانة حسب الجدول."),
    ],
  }),
  sop("ohs", 5, {
    title: "Safe Knife & Cutting-Machine Handling",
    titleAr: "التعامل الآمن مع السكاكين وآلات التقطيع",
    subtitle: "Cut-resistant gloves, blade guards, machine guarding & sharpening",
    subtitleAr: "قفازات مقاومة للقطع، واقيات الشفرات، تحصين الآلات، والسنّ الآمن",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Prevent cut and laceration injuries from knives, slicers, grinders and mincers.",
        "منع إصابات القطع والجروح من السكاكين وآلات التقطيع والطحن والفرم."),
      S("2. Scope", "٢. النطاق",
        "All manual knives and powered cutting/grinding machines and their operators.",
        "كل السكاكين اليدوية وآلات التقطيع/الطحن الكهربائية ومشغّليها."),
      S("3. Procedure", "٣. الإجراء",
        "1) Wear cut-resistant gloves and a chain-mesh apron where required.\n2) Use the correct sharp knife for the task; a blunt knife is more dangerous.\n3) Cut away from the body on a stable surface; never catch a falling knife.\n4) Carry knives point-down beside the body; store in a sheath/rack, never in sinks.\n5) Powered machines: guards in place, no reaching into moving parts, isolate before clearing jams (LOTO — SOP-OHS-08).\n6) Report any damaged blade or guard immediately.",
        "١) ارتداء قفازات مقاومة للقطع ومريلة شبكية معدنية حيثما يلزم.\n٢) استخدام السكين الحاد الصحيح للمهمة؛ السكين الكليل أخطر.\n٣) القطع بعيداً عن الجسم على سطح ثابت؛ لا تمسك سكيناً ساقطاً.\n٤) حمل السكاكين والرأس لأسفل بجانب الجسم؛ تخزينها في غمد/حامل، لا في الأحواض.\n٥) الآلات الكهربائية: الواقيات في مكانها، لا مدّ اليد للأجزاء المتحركة، العزل قبل إزالة الانحشار (LOTO — SOP-OHS-08).\n٦) الإبلاغ الفوري عن أي شفرة أو واقٍ تالف."),
      S("4. Records", "٤. السجلات",
        "Knife issue/return log, machine guard inspection log, cut-injury incident records, training records.",
        "سجل صرف/إعادة السكاكين، سجل فحص واقيات الآلات، سجلات إصابات القطع، سجلات التدريب."),
      S("5. Frequency", "٥. التكرار",
        "Every shift (issue/return & guard check); training on hire + annually.",
        "كل وردية (الصرف/الإعادة وفحص الواقيات)؛ التدريب عند التعيين + سنوياً."),
    ],
  }),
  sop("ohs", 6, {
    title: "Safe Manual Lifting & Trolley Handling",
    titleAr: "الرفع اليدوي الآمن للأحمال والتعامل مع العربات",
    subtitle: "25 kg limit, correct technique, trolley inspection & job rotation",
    subtitleAr: "حد ٢٥ كغم، الأسلوب الصحيح، فحص العربات، وتناوب المهام",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Prevent back and musculoskeletal injuries from manual lifting and trolley movement by defining weight limits, correct technique, and trolley inspection/usage requirements.",
        "منع إصابات الظهر والجهاز العضلي الهيكلي الناتجة عن الرفع اليدوي وتحريك العربات، عبر تحديد الحدود الوزنية والأسلوب الصحيح واشتراطات فحص واستخدام العربات."),
      S("2. Scope", "٢. النطاق",
        "All staff in receiving, production, stores, chillers/freezers, kitchen and loading, and every manual trolley or pallet jack on site.",
        "كل العاملين في الاستلام والإنتاج والمخازن وغرف التبريد والتجميد والمطبخ والتحميل، وكل عربة يدوية أو رافعة بليت مستخدمة في الموقع."),
      S("3. Lifting Technique", "٣. أسلوب الرفع",
        "1) Assess the load before lifting (weight/shape/stability/floor) and plan the route.\n2) Max 25 kg single-person lift — above that, team lift or use a trolley.\n3) Feet shoulder-width, bend the knees not the back, firm grip, load close to the body, lift with the leg muscles.\n4) No twisting of the torso while carrying — pivot the feet.\n5) Job rotation every 1–2 hours for repetitive tasks.",
        "١) قيّم الحمل قبل الرفع (الوزن/الشكل/الثبات/الأرضية) وخطّط المسار.\n٢) حد أقصى ٢٥ كغم للرفع الفردي — فوق ذلك: رفع جماعي أو عربة.\n٣) قدمان بعرض الكتفين، ثني الركبتين لا الظهر، إمساك محكم، الحمل قريب من الجسم، الرفع بعضلات الساقين.\n٤) لا التفاف بالجذع أثناء الحمل — أدِر قدميك.\n٥) تناوب المهام كل ١-٢ ساعة للمهام المتكررة."),
      S("4. Trolley Handling", "٤. التعامل مع العربات",
        "1) Pre-use check: wheels roll freely, no broken parts, handles intact, brakes work — any defect = OUT OF SERVICE tag + maintenance request.\n2) Loading: never exceed rated capacity, heavy at bottom / light on top, even distribution, must not block line of sight, secure tall loads.\n3) Movement: push don't pull, both hands on the handle, walking pace only, wide gradual turns, no sudden stops.\n4) Ramps: push uphill with both hands (two people for heavy loads), stay uphill going down, never leave a trolley on a slope.\n5) Brakes: engage at every stop, before loading/unloading and before stepping away.\n6) Parking: never block aisles, fire exits, extinguishers or electrical panels — return trolleys to the designated bay.",
        "١) فحص قبل الاستخدام: العجلات تدور بحرية، لا أجزاء مكسورة، المقابض سليمة، الفرامل تعمل — أي عطل = بطاقة \"خارج الخدمة\" + طلب صيانة.\n٢) التحميل: لا تتجاوز السعة المصمّمة، الثقيل أسفل والخفيف أعلى، توزيع متوازن، لا يحجب الرؤية، تثبيت الأحمال العالية.\n٣) التحريك: ادفع ولا تسحب، اليدان معاً على المقبض، سرعة المشي فقط، منعطفات واسعة تدريجية، لا توقف مفاجئ.\n٤) المنحدرات: الدفع صعوداً بيدين (شخصان للأحمال الثقيلة)، البقاء في الجهة العليا نزولاً، لا ترك عربة على منحدر.\n٥) الفرامل: فعّلها عند كل توقف وقبل التحميل/التفريغ وقبل الابتعاد.\n٦) الإيقاف: لا سدّ الممرات أو مخارج الطوارئ أو الطفايات أو لوحات الكهرباء — إعادة العربة لمكانها المخصص."),
      S("5. Records", "٥. السجلات",
        "Manual-handling training records (signed per employee), manual-handling risk assessment per area, trolley inspection/maintenance log, OUT OF SERVICE tags, incident and near-miss reports, job-rotation schedule.",
        "سجلات تدريب المناولة اليدوية (موقّعة لكل موظف)، تقييم مخاطر المناولة لكل منطقة، سجل فحص/صيانة العربات، بطاقات \"خارج الخدمة\"، تقارير الحوادث وشبه الحوادث، جدول تناوب المهام."),
      S("6. Frequency", "٦. التكرار",
        "Trolley check: every shift | Training: on hire + annually | Risk-assessment review: annually.",
        "فحص العربة: كل وردية | التدريب: عند التعيين + سنوياً | مراجعة تقييم المخاطر: سنوياً."),
    ],
  }),
  sop("ohs", 7, {
    title: "Work Permit System",
    titleAr: "نظام تصاريح العمل",
    subtitle: "Hot work, confined space, work at height & electrical permits",
    subtitleAr: "تصاريح العمل الساخن والحيّز المحصور والعمل على ارتفاع والكهرباء",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Control high-risk activities through a formal permit that verifies hazards are assessed and controls are in place before work starts.",
        "التحكم في الأنشطة عالية الخطورة عبر تصريح رسمي يتحقق من تقييم المخاطر ووجود الضوابط قبل بدء العمل."),
      S("2. Scope", "٢. النطاق",
        "Hot work (welding/cutting/grinding), confined-space entry, work at height, electrical isolation, and contractor high-risk tasks.",
        "العمل الساخن (لحام/قطع/جلخ)، دخول الحيّز المحصور، العمل على ارتفاع، العزل الكهربائي، ومهام المقاولين عالية الخطورة."),
      S("3. Procedure", "٣. الإجراء",
        "1) Requester completes the permit and risk assessment before work.\n2) HSE / authorised person reviews controls (isolation, fire watch, gas test, ventilation, rescue plan).\n3) Permit issued with defined validity, scope and controls; displayed at the worksite.\n4) Verify controls on site before start; monitor during work.\n5) Close and sign off the permit on completion; restore area to safe state.\n6) Hot work: fire watch during and for 30 minutes after.",
        "١) يكمل الطالب التصريح وتقييم المخاطر قبل العمل.\n٢) HSE/الشخص المخوّل يراجع الضوابط (العزل، مراقبة الحريق، اختبار الغازات، التهوية، خطة الإنقاذ).\n٣) إصدار التصريح بمدة ونطاق وضوابط محددة؛ يُعرض في موقع العمل.\n٤) التحقق من الضوابط ميدانياً قبل البدء؛ المراقبة أثناء العمل.\n٥) إغلاق التصريح وتوقيعه عند الإنجاز؛ إعادة المنطقة لحالة آمنة.\n٦) العمل الساخن: مراقبة حريق أثناءه ولمدة ٣٠ دقيقة بعده."),
      S("4. Records", "٤. السجلات",
        "Work Permit form F-07 (issued & closed, signed), attached risk assessments / method statements, gas-test records, permit register / log.",
        "نموذج تصريح العمل F-07 (مُصدر ومغلق وموقّع)، تقييمات المخاطر/بيانات الطريقة المرفقة، سجلات اختبار الغازات، سجل/دفتر التصاريح."),
      S("5. Frequency", "٥. التكرار",
        "Per task; Work Permit F-07 valid for one shift or the defined period only.",
        "لكل مهمة؛ تصريح العمل F-07 صالح لوردية واحدة أو المدة المحددة فقط."),
    ],
  }),
  sop("ohs", 8, {
    title: "Lockout / Tagout (LOTO)",
    titleAr: "قفل ووسم المعدات أثناء الصيانة",
    subtitle: "Energy isolation of machinery before cleaning or maintenance",
    subtitleAr: "عزل مصادر الطاقة عن الآلات قبل التنظيف أو الصيانة",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Prevent injury from unexpected start-up or release of stored energy during cleaning, servicing or clearing jams.",
        "منع الإصابة من التشغيل المفاجئ أو انطلاق الطاقة المخزّنة أثناء التنظيف أو الصيانة أو إزالة الانحشار."),
      S("2. Scope", "٢. النطاق",
        "All powered machinery and energy sources (electrical, mechanical, pneumatic, hydraulic, thermal) during maintenance.",
        "كل الآلات الكهربائية ومصادر الطاقة (كهربائية، ميكانيكية، هوائية، هيدروليكية، حرارية) أثناء الصيانة."),
      S("3. Procedure", "٣. الإجراء",
        "1) Notify affected staff and shut down the equipment normally.\n2) Isolate all energy sources at the disconnect.\n3) Apply the personal lock and tag; each worker uses their own lock.\n4) Release/restrain stored energy (bleed pressure, block moving parts).\n5) Verify zero energy (try-start test) before work.\n6) On completion: remove tools, confirm all clear, remove locks/tags in reverse and restore power.",
        "١) إبلاغ الموظفين المتأثرين وإيقاف المعدة بشكل طبيعي.\n٢) عزل كل مصادر الطاقة عند نقطة الفصل.\n٣) وضع القفل والبطاقة الشخصية؛ كل عامل يستخدم قفله الخاص.\n٤) تفريغ/تقييد الطاقة المخزّنة (تفريغ الضغط، تثبيت الأجزاء المتحركة).\n٥) التحقق من انعدام الطاقة (اختبار محاولة تشغيل) قبل العمل.\n٦) عند الإنجاز: إزالة الأدوات، تأكيد السلامة، إزالة الأقفال/البطاقات بترتيب عكسي وإعادة الطاقة."),
      S("4. Records", "٤. السجلات",
        "LOTO register, machine-specific isolation procedures, padlock/tag issue log, training records.",
        "سجل LOTO، إجراءات العزل الخاصة بكل آلة، سجل صرف الأقفال/البطاقات، سجلات التدريب."),
      S("5. Frequency", "٥. التكرار",
        "Every maintenance/cleaning task on powered equipment; procedure review annually.",
        "كل مهمة صيانة/تنظيف على معدة كهربائية؛ مراجعة الإجراء سنوياً."),
    ],
  }),
  sop("ohs", 9, {
    title: "Incident & Near-Miss Reporting + Investigation",
    titleAr: "الإبلاغ عن الحوادث وشبه الحوادث والتحقيق",
    subtitle: "Report, investigate (5 Whys / root cause) and corrective action",
    subtitleAr: "الإبلاغ والتحقيق (5 لماذا / السبب الجذري) والإجراء التصحيحي",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Ensure all incidents and near-misses are reported, investigated and used to prevent recurrence.",
        "ضمان الإبلاغ عن كل الحوادث وشبه الحوادث والتحقيق فيها واستخدامها لمنع التكرار."),
      S("2. Scope", "٢. النطاق",
        "All injuries, property damage, fires, spills, and near-misses involving employees, contractors or visitors.",
        "كل الإصابات وأضرار الممتلكات والحرائق والانسكابات وشبه الحوادث التي تشمل الموظفين أو المقاولين أو الزوار."),
      S("3. Procedure", "٣. الإجراء",
        "1) Make the scene safe and provide first aid (SOP-EM-04).\n2) Report to the supervisor/HSE immediately; log within the shift.\n3) HSE opens the incident report and preserves evidence/photos.\n4) Investigate using 5 Whys / root-cause analysis.\n5) Define corrective/preventive actions with owners and due dates.\n6) Verify effectiveness and share lessons learned.",
        "١) تأمين موقع الحادث وتقديم الإسعاف الأولي (SOP-EM-04).\n٢) الإبلاغ للمشرف/HSE فوراً؛ التسجيل خلال الوردية.\n٣) HSE يفتح تقرير الحادث ويحفظ الأدلة/الصور.\n٤) التحقيق باستخدام 5 لماذا / تحليل السبب الجذري.\n٥) تحديد الإجراءات التصحيحية/الوقائية مع المسؤولين والمواعيد.\n٦) التحقق من الفعالية ومشاركة الدروس المستفادة."),
      S("4. Records", "٤. السجلات",
        "Incident/near-miss report, investigation & root-cause report, CAPA log, statistics/trend review.",
        "تقرير الحادث/شبه الحادث، تقرير التحقيق والسبب الجذري، سجل CAPA، مراجعة الإحصاءات/الاتجاهات."),
      S("5. Frequency", "٥. التكرار",
        "On every incident/near-miss; trend review monthly.",
        "عند كل حادث/شبه حادث؛ مراجعة الاتجاهات شهرياً."),
    ],
  }),
  sop("ohs", 10, {
    title: "Periodic Occupational Medical Check",
    titleAr: "الفحص الطبي الدوري للعاملين",
    subtitle: "Fitness-to-work, food-handler health cards & role-specific screening",
    subtitleAr: "اللياقة للعمل، البطاقات الصحية لمتداولي الغذاء، والفحص حسب الدور",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Confirm workers are fit for their role and protect food safety by keeping valid food-handler health cards.",
        "التأكد من لياقة العاملين لأدوارهم وحماية سلامة الغذاء بالحفاظ على بطاقات صحية سارية لمتداولي الغذاء."),
      S("2. Scope", "٢. النطاق",
        "All food handlers and staff in physically demanding or hazard-exposed roles.",
        "كل متداولي الغذاء والعاملين في الأدوار الشاقة بدنياً أو المعرّضة للمخاطر."),
      S("3. Procedure", "٣. الإجراء",
        "1) Pre-employment medical and food-handler card before first shift.\n2) Periodic renewal per Dubai Municipality / MOH requirements.\n3) Role-specific screening (e.g. cold exposure, manual handling) as required.\n4) Remove symptomatic food handlers from duty until cleared (link SOP-FS Personnel Hygiene).\n5) Track card validity and send renewal reminders.",
        "١) فحص طبي قبل التوظيف وبطاقة متداول غذاء قبل أول وردية.\n٢) تجديد دوري وفق متطلبات بلدية دبي / وزارة الصحة.\n٣) فحص حسب الدور (مثل التعرّض للبرد، المناولة اليدوية) عند اللزوم.\n٤) إبعاد متداولي الغذاء المصابين بالأعراض حتى الموافقة على عودتهم.\n٥) تتبّع صلاحية البطاقات وإرسال تذكيرات التجديد."),
      S("4. Records", "٤. السجلات",
        "Medical fitness certificates, food-handler health cards, screening results, renewal tracker.",
        "شهادات اللياقة الطبية، البطاقات الصحية لمتداولي الغذاء، نتائج الفحص، متتبّع التجديد."),
      S("5. Frequency", "٥. التكرار",
        "On hire + periodic renewal per regulation; role-specific as required.",
        "عند التعيين + تجديد دوري وفق اللوائح؛ حسب الدور عند اللزوم."),
    ],
  }),
  sop("ohs", 11, {
    title: "Toolbox Talk / Daily Safety Briefing",
    titleAr: "اجتماع السلامة اليومي (Toolbox Talk)",
    subtitle: "Short pre-shift briefing on the day's hazards, controls & attendance",
    subtitleAr: "إحاطة قصيرة قبل الوردية عن مخاطر اليوم وضوابطها مع تسجيل الحضور",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Communicate the day's tasks, specific hazards and controls to the team before work starts and reinforce safe behaviour.",
        "إيصال مهام اليوم ومخاطرها المحددة وضوابطها للفريق قبل بدء العمل وترسيخ السلوك الآمن."),
      S("2. Scope", "٢. النطاق",
        "All operational teams (production, stores, cold rooms, dispatch, maintenance) at the start of each shift or before a specific high-risk task.",
        "كل فرق التشغيل (الإنتاج، المخازن، الغرف الباردة، الشحن، الصيانة) عند بداية كل وردية أو قبل مهمة محددة عالية الخطورة."),
      S("3. Procedure", "٣. الإجراء",
        "1) Supervisor selects the topic (task of the day, a recent incident/near-miss, a seasonal hazard, or a recurring finding).\n2) Deliver a short 5–10 minute briefing: hazards, required PPE, controls, emergency arrangements.\n3) Encourage workers to raise concerns and confirm understanding.\n4) Record attendance and topic on the Toolbox Talk attendance form (workers sign).\n5) Escalate any hazard that cannot be controlled on the spot to HSE.\n6) File the signed record and track topics covered.",
        "١) يختار المشرف الموضوع (مهمة اليوم، حادث/شبه حادث حديث، خطر موسمي، أو ملاحظة متكررة).\n٢) تقديم إحاطة قصيرة ٥-١٠ دقائق: المخاطر، معدات الوقاية المطلوبة، الضوابط، ترتيبات الطوارئ.\n٣) تشجيع العمال على طرح المخاوف وتأكيد الفهم.\n٤) تسجيل الحضور والموضوع على نموذج حضور Toolbox Talk (توقيع العمال).\n٥) تصعيد أي خطر لا يمكن ضبطه فوراً إلى HSE.\n٦) حفظ السجل الموقّع وتتبّع المواضيع المغطاة."),
      S("4. Records", "٤. السجلات",
        "Toolbox Talk attendance form (topic, date, presenter, signed attendees), topic tracker, escalated-hazard actions.",
        "نموذج حضور Toolbox Talk (الموضوع، التاريخ، المُقدِّم، الحضور الموقّعون)، متتبّع المواضيع، إجراءات المخاطر المصعّدة."),
      S("5. Frequency", "٥. التكرار",
        "Every shift / daily, and before any specific high-risk task.",
        "كل وردية / يومياً، وقبل أي مهمة محددة عالية الخطورة."),
    ],
  }),
  sop("ohs", 12, {
    title: "Labour Welfare (F-34)",
    titleAr: "رعاية العمالة (F-34)",
    subtitle: "Drinking water, rest areas, heat-stress control, sanitation & welfare checks",
    subtitleAr: "مياه الشرب، مناطق الراحة، مكافحة الإجهاد الحراري، الإصحاح، وفحوصات الرعاية",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Protect worker health and wellbeing by providing adequate welfare facilities (water, rest, sanitation) and controlling heat stress and fatigue.",
        "حماية صحة العمال ورفاههم بتوفير مرافق رعاية كافية (مياه، راحة، إصحاح) والتحكم بالإجهاد الحراري والإرهاق."),
      S("2. Scope", "٢. النطاق",
        "All workers on site, with attention to those in hot/outdoor areas, cold rooms and physically demanding roles.",
        "كل العمال في الموقع، مع الاهتمام بمن يعملون في المناطق الحارة/الخارجية والغرف الباردة والأدوار الشاقة بدنياً."),
      S("3. Procedure", "٣. الإجراء",
        "1) Provide cool drinking water, clean toilets, hand-wash facilities and a shaded/air-conditioned rest area.\n2) Apply the midday break rule and heat-stress controls during summer (hydration, rotation, shade).\n3) Provide adequate breaks for cold-room and heavy-task workers; monitor for fatigue/heat symptoms.\n4) Keep welfare facilities clean and stocked; inspect on a schedule using the Labour Welfare form F-34.\n5) Provide first-aid access and a means to report welfare concerns.\n6) Act on findings and record corrective actions.",
        "١) توفير مياه شرب باردة ودورات مياه نظيفة ومرافق غسيل أيدٍ ومنطقة راحة مظللة/مكيّفة.\n٢) تطبيق قاعدة راحة الظهيرة وضوابط الإجهاد الحراري صيفاً (الترطيب، التناوب، التظليل).\n٣) توفير فترات راحة كافية لعمال الغرف الباردة والمهام الثقيلة؛ مراقبة أعراض الإرهاق/الحرارة.\n٤) إبقاء مرافق الرعاية نظيفة ومجهّزة؛ الفحص وفق جدول باستخدام نموذج رعاية العمالة F-34.\n٥) توفير وصول للإسعاف ووسيلة للإبلاغ عن مخاوف الرعاية.\n٦) التصرف بناءً على النتائج وتسجيل الإجراءات التصحيحية."),
      S("4. Records", "٤. السجلات",
        "Labour Welfare inspection form F-34, drinking-water & facility cleaning logs, heat-stress / midday-break records, welfare corrective actions.",
        "نموذج فحص رعاية العمالة F-34، سجلات مياه الشرب وتنظيف المرافق، سجلات الإجهاد الحراري/راحة الظهيرة، الإجراءات التصحيحية للرعاية."),
      S("5. Frequency", "٥. التكرار",
        "Welfare inspection weekly (F-34); heat-stress controls daily in summer.",
        "فحص الرعاية أسبوعياً (F-34)؛ ضوابط الإجهاد الحراري يومياً في الصيف."),
    ],
  }),

  // ══════════════════════════════════════════════════════════════════════
  // EMERGENCY
  // ══════════════════════════════════════════════════════════════════════
  sop("em", 1, {
    title: "Fire & Evacuation Response Plan",
    titleAr: "خطة الاستجابة للحرائق والإخلاء",
    subtitle: "Alarm, evacuation routes, assembly point, roll-call & drills",
    subtitleAr: "الإنذار، مسارات الإخلاء، نقطة التجمّع، النداء، والتجارب",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Ensure a safe, rapid and orderly evacuation and effective first response in the event of fire.",
        "ضمان إخلاء آمن وسريع ومنظّم واستجابة أولية فعّالة في حال نشوب حريق."),
      S("2. Scope", "٢. النطاق",
        "All buildings, cold stores, offices and yard areas; all employees, contractors and visitors.",
        "كل المباني والمخازن الباردة والمكاتب والساحات؛ كل الموظفين والمقاولين والزوار."),
      S("3. Procedure", "٣. الإجراء",
        "1) On discovering fire: raise the alarm and call Civil Defence (997).\n2) Only tackle small fires with the correct extinguisher if trained and safe to do so.\n3) On alarm: stop work, shut down where safe, evacuate by the nearest route — do not use lifts.\n4) Fire wardens sweep areas and direct people to the assembly point.\n5) Roll-call at the assembly point; report anyone missing to Civil Defence.\n6) Do not re-enter until the all-clear is given.",
        "١) عند اكتشاف الحريق: إطلاق الإنذار والاتصال بالدفاع المدني (٩٩٧).\n٢) لا تكافح إلا الحرائق الصغيرة بالطفاية الصحيحة إن كنت مدرَّباً والوضع آمن.\n٣) عند الإنذار: أوقف العمل، أغلق حيث يكون آمناً، أخلِ من أقرب مسار — لا تستخدم المصاعد.\n٤) مراقبو الحريق يمشّطون المناطق ويوجّهون الأشخاص لنقطة التجمّع.\n٥) نداء الأسماء عند نقطة التجمّع؛ إبلاغ الدفاع المدني عن أي مفقود.\n٦) عدم العودة حتى إعطاء إشارة الأمان."),
      S("4. Records", "٤. السجلات",
        "Fire drill records, extinguisher/alarm inspection logs, warden list, emergency contact list, evacuation plan drawings.",
        "سجلات تجارب الحريق، سجلات فحص الطفايات/الإنذار، قائمة المراقبين، قائمة جهات الطوارئ، مخططات الإخلاء."),
      S("5. Frequency", "٥. التكرار",
        "Evacuation drill at least twice a year; equipment inspections monthly.",
        "تجربة إخلاء مرتين سنوياً على الأقل؛ فحص المعدات شهرياً."),
    ],
  }),
  sop("em", 2, {
    title: "Ammonia / Refrigerant Leak Response",
    titleAr: "الاستجابة لتسرب الأمونيا أو غازات التبريد",
    subtitle: "Detection, evacuation, isolation & specialist response",
    subtitleAr: "الكشف، الإخلاء، العزل، والاستجابة المتخصصة",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Protect people from toxic/flammable refrigerant exposure and control leaks safely.",
        "حماية الأشخاص من التعرّض للغازات التبريدية السامة/القابلة للاشتعال والسيطرة على التسرّب بأمان."),
      S("2. Scope", "٢. النطاق",
        "All refrigeration plant, engine rooms and cold stores using ammonia or other refrigerants.",
        "كل معدات التبريد وغرف المحركات والمخازن الباردة التي تستخدم الأمونيا أو غازات تبريد أخرى."),
      S("3. Procedure", "٣. الإجراء",
        "1) On detection (alarm/smell): evacuate the area immediately upwind and raise the alarm.\n2) Call Civil Defence (997); notify the maintenance/refrigeration lead.\n3) Do not enter the leak area without proper respiratory PPE — trained/authorised responders only.\n4) Isolate the affected plant if safe to do so from outside.\n5) Account for personnel at the assembly point; provide first aid for any exposure.\n6) Ventilate and re-enter only after gas readings are safe and the all-clear is given.",
        "١) عند الكشف (إنذار/رائحة): إخلاء المنطقة فوراً باتجاه الريح وإطلاق الإنذار.\n٢) الاتصال بالدفاع المدني (٩٩٧)؛ إبلاغ مسؤول الصيانة/التبريد.\n٣) لا تدخل منطقة التسرّب دون معدات وقاية تنفسية مناسبة — للمستجيبين المدرَّبين/المخوّلين فقط.\n٤) عزل المعدة المتأثرة إن أمكن بأمان من الخارج.\n٥) حصر الأشخاص عند نقطة التجمّع؛ تقديم الإسعاف لأي تعرّض.\n٦) التهوية وعدم العودة إلا بعد قراءات غاز آمنة وإشارة الأمان."),
      S("4. Records", "٤. السجلات",
        "Refrigerant leak/incident report, gas-detector calibration & inspection logs, plant isolation records, drill records.",
        "تقرير تسرّب/حادث الغاز، سجلات معايرة وفحص كواشف الغاز، سجلات عزل المعدات، سجلات التجارب."),
      S("5. Frequency", "٥. التكرار",
        "On any leak; detector checks per schedule; response drill annually.",
        "عند أي تسرّب؛ فحص الكواشف حسب الجدول؛ تجربة الاستجابة سنوياً."),
    ],
  }),
  sop("em", 3, {
    title: "Extended Power / Cold-Storage Outage Response",
    titleAr: "الاستجابة لانقطاع الكهرباء المطوّل",
    subtitle: "Generator, door discipline, temperature protection & product decisions",
    subtitleAr: "المولّد، انضباط الأبواب، حماية الحرارة، وقرارات المنتج",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Protect the cold chain and stored product during power failure and decide on product disposition safely.",
        "حماية سلسلة التبريد والمنتج المخزّن أثناء انقطاع الكهرباء واتخاذ قرار آمن بشأن المنتج."),
      S("2. Scope", "٢. النطاق",
        "All chillers, freezers and refrigerated areas during mains power interruption.",
        "كل غرف التبريد والتجميد والمناطق المبرّدة أثناء انقطاع التيار الرئيسي."),
      S("3. Procedure", "٣. الإجراء",
        "1) Confirm the outage and start/verify the standby generator; prioritise cold-store loads.\n2) Keep cold-room doors closed — strict door discipline; no loading/picking during outage.\n3) Monitor and log room temperatures more frequently.\n4) If temperatures approach limits, follow SOP-FS-03 (deviation) for product hold/assessment.\n5) Escalate to maintenance and management; arrange contingency (extra ice, transfer to backup store).\n6) After restoration: verify temperatures recovered and assess product before release.",
        "١) تأكيد الانقطاع وتشغيل/التحقق من المولّد الاحتياطي؛ إعطاء الأولوية لأحمال التخزين البارد.\n٢) إبقاء أبواب الغرف الباردة مغلقة — انضباط صارم للأبواب؛ لا تحميل/تجهيز أثناء الانقطاع.\n٣) مراقبة وتسجيل حرارة الغرف بوتيرة أعلى.\n٤) إذا اقتربت الحرارة من الحدود، اتّبع SOP-FS-03 (الانحراف) لحجز/تقييم المنتج.\n٥) التصعيد للصيانة والإدارة؛ ترتيب خطة طوارئ (ثلج إضافي، نقل لمخزن احتياطي).\n٦) بعد العودة: التحقق من تعافي الحرارة وتقييم المنتج قبل الإفراج."),
      S("4. Records", "٤. السجلات",
        "Outage log, generator test/run records, temperature logs during outage, product disposition records.",
        "سجل الانقطاع، سجلات اختبار/تشغيل المولّد، سجلات الحرارة أثناء الانقطاع، سجلات مصير المنتج."),
      S("5. Frequency", "٥. التكرار",
        "On any outage; generator test monthly.",
        "عند أي انقطاع؛ اختبار المولّد شهرياً."),
    ],
  }),
  sop("em", 4, {
    title: "Major Injury & First-Aid Response",
    titleAr: "الاستجابة للإصابات الجسيمة والإسعافات الأولية",
    subtitle: "DRABC primary survey, ambulance call (998) & incident escalation",
    subtitleAr: "الفحص الأولي DRABC، الاتصال بالإسعاف (٩٩٨)، وتصعيد الحادث",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Define exactly what to do when an accident or injury occurs — preserve life, prevent the condition worsening, ensure fast correct escalation to medical care, and document for investigation.",
        "تحديد ما يجب فعله بالضبط عند وقوع حادث أو إصابة — حفظ الحياة، ومنع تفاقم الحالة، وضمان تصعيد سريع وصحيح للرعاية الطبية، وتوثيق الحادث للتحقيق."),
      S("2. Scope", "٢. النطاق",
        "All accidents and injuries in production, warehouses, kitchen, chillers, loading and offices — for all employees, contractors and visitors.",
        "كل الحوادث والإصابات في الإنتاج والمستودعات والمطبخ وغرف التبريد والتحميل والمكاتب — لكل الموظفين والمقاولين والزوار."),
      S("3. Immediate Response", "٣. الاستجابة الفورية",
        "1) Stay calm; do not crowd the casualty.\n2) Immediately call the on-shift first aider and HSE Officer (names/numbers on the F-31 list posted in every area).\n3) Apply the DRABC primary survey: Danger → Response → Airway → Breathing → Compressions.\n4) Make the scene safe first — electricity, machinery, spill, ammonia.\n5) First aider / HSE Officer assesses injury severity.",
        "١) ابقَ هادئاً ولا تتجمهر حول المصاب.\n٢) اتصل فوراً بالمسعف المناوب وضابط HSE (الأسماء/الأرقام على قائمة F-31 المعلّقة في كل منطقة).\n٣) طبّق الفحص الأولي DRABC: خطر ← استجابة ← مجرى الهواء ← التنفس ← الضغطات.\n٤) أمّن مكان الحادث أولاً — كهرباء، آلات، انسكاب، أمونيا.\n٥) المسعف/ضابط HSE يقيّم شدة الإصابة."),
      S("4. Escalation", "٤. التصعيد",
        "6) Minor case → first aid at the company clinic + entry in the treatment log.\n7) Major/severe case → call ambulance 998 (Police 999, Civil Defence 997, Unified 112); do not move the casualty unless danger is ongoing.\n8) Assign one person to meet and guide the ambulance at the gate.\n9) Escort the casualty to hospital and notify next of kin.\n10) Isolate the scene and preserve evidence/photos before cleaning.\n11) HSE opens Incident Report F-01 within one hour and conducts the investigation and 5 Whys.\n12) Serious injuries reported to MOHRE within 24 hours; restock the used first-aid kit.",
        "٦) حالة بسيطة ← إسعاف أولي في عيادة الشركة + تسجيل في سجل العلاج.\n٧) حالة خطيرة ← اتصال بالإسعاف ٩٩٨ (الشرطة ٩٩٩، الدفاع المدني ٩٩٧، الموحّد ١١٢)؛ لا تُحرَّك الضحية إلا عند خطر مستمر.\n٨) تعيين شخص لاستقبال سيارة الإسعاف عند البوابة وإرشادها.\n٩) مرافقة المصاب للمستشفى وإبلاغ عائلته.\n١٠) عزل موقع الحادث وحفظ الأدلة/الصور قبل التنظيف.\n١١) HSE يفتح تقرير الحادث F-01 خلال ساعة ويجري التحقيق و5 لماذا.\n١٢) الإصابات الجسيمة تُبلَّغ لوزارة الموارد البشرية (MOHRE) خلال ٢٤ ساعة؛ إعادة تزويد حقيبة الإسعاف المستخدمة."),
      S("5. Records", "٥. السجلات",
        "Incident Report F-01, first-aid treatment log, witness statements, investigation & root-cause report, register of certified first aiders, monthly first-aid kit inspection log, F-31 Emergency Contacts list, MOHRE notification, return-to-work records.",
        "تقرير الحادث F-01، سجل العلاج الإسعافي، إفادات الشهود، تقرير التحقيق والسبب الجذري، سجل المسعفين المعتمدين، سجل فحص حقائب الإسعاف الشهري، قائمة جهات الطوارئ F-31، إبلاغ MOHRE، سجلات العودة للعمل."),
      S("6. Frequency", "٦. التكرار",
        "Every incident | First-aid kit check: monthly | First-aider training: renew every 2 years | Procedure review: annually.",
        "عند كل حادث | فحص حقائب الإسعاف: شهري | تدريب المسعفين: تجديد كل سنتين | مراجعة الإجراء: سنوياً."),
    ],
  }),

  // ══════════════════════════════════════════════════════════════════════
  // ENVIRONMENT
  // ══════════════════════════════════════════════════════════════════════
  sop("en", 1, {
    title: "Organic & Solid Waste Management",
    titleAr: "إدارة النفايات العضوية والصلبة",
    subtitle: "Segregation, chilled waste holding, licensed collection & records",
    subtitleAr: "الفصل، حفظ النفايات مبرّدة، النقل المرخّص، والسجلات",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Manage meat and general waste hygienically and lawfully to prevent contamination, pests and environmental harm.",
        "إدارة نفايات اللحوم والنفايات العامة بشكل صحي وقانوني لمنع التلوث والحشرات والأضرار البيئية."),
      S("2. Scope", "٢. النطاق",
        "All solid, organic (meat by-product) and packaging waste generated on site.",
        "كل النفايات الصلبة والعضوية (مخلفات اللحوم) ونفايات التغليف المتولّدة في الموقع."),
      S("3. Procedure", "٣. الإجراء",
        "1) Segregate waste at source into labelled, colour-coded, covered bins.\n2) Hold organic/meat waste in a dedicated chilled/closed area to control odour and pests.\n3) Remove waste from production frequently; keep bins clean and lidded.\n4) Dispose only via municipality-approved licensed contractors; keep manifests.\n5) Condemned/expired product destruction is documented (link SOP-FS-09).\n6) Clean and disinfect the waste area on schedule.",
        "١) فصل النفايات من المصدر في حاويات موسومة ومرمّزة بالألوان ومغطاة.\n٢) حفظ النفايات العضوية/اللحوم في منطقة مبرّدة/مغلقة مخصصة للتحكم بالرائحة والحشرات.\n٣) إزالة النفايات من الإنتاج بشكل متكرر؛ إبقاء الحاويات نظيفة ومغطاة.\n٤) التخلص فقط عبر مقاولين مرخّصين معتمدين من البلدية؛ الاحتفاظ بالمستندات.\n٥) إتلاف المنتج المدان/المنتهي موثّق (ربط SOP-FS-09).\n٦) تنظيف وتطهير منطقة النفايات حسب الجدول."),
      S("4. Records", "٤. السجلات",
        "Waste collection manifests, licensed-contractor certificates, waste-area cleaning log, destruction certificates.",
        "مستندات جمع النفايات، شهادات المقاول المرخّص، سجل تنظيف منطقة النفايات، شهادات الإتلاف."),
      S("5. Frequency", "٥. التكرار",
        "Continuous segregation; collection per schedule; area cleaning daily.",
        "فصل مستمر؛ الجمع حسب الجدول؛ تنظيف المنطقة يومياً."),
    ],
  }),
  sop("en", 2, {
    title: "Wastewater & Grease-Trap Management",
    titleAr: "إدارة المياه العادمة ومصائد الدهون",
    subtitle: "Grease-trap cleaning, effluent control & licensed disposal",
    subtitleAr: "تنظيف مصائد الدهون، ضبط الصرف، والتخلص المرخّص",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Prevent drain blockage, odour and environmental non-compliance from fats, oils and grease (FOG) and process effluent.",
        "منع انسداد المصارف والروائح وعدم الامتثال البيئي الناتج عن الدهون والزيوت والشحوم (FOG) ومياه المعالجة."),
      S("2. Scope", "٢. النطاق",
        "All floor drains, grease traps and wastewater discharge points on site.",
        "كل مصارف الأرضيات ومصائد الدهون ونقاط تصريف المياه العادمة في الموقع."),
      S("3. Procedure", "٣. الإجراء",
        "1) Scrape solids to waste before washdown — do not flush solids/fat to drains.\n2) Clean grease traps on schedule; record levels and cleaning.\n3) Use licensed tankers for grease/effluent removal; retain manifests.\n4) Keep drains and interceptors free-flowing; report blockages immediately.\n5) Do not discharge prohibited chemicals to drains.",
        "١) كشط المواد الصلبة إلى النفايات قبل الغسل — لا تصرف الصلبة/الدهون في المصارف.\n٢) تنظيف مصائد الدهون حسب الجدول؛ تسجيل المستويات والتنظيف.\n٣) استخدام صهاريج مرخّصة لنقل الدهون/الصرف؛ الاحتفاظ بالمستندات.\n٤) إبقاء المصارف والفواصل انسيابية؛ الإبلاغ الفوري عن الانسدادات.\n٥) عدم تصريف المواد الكيميائية المحظورة في المصارف."),
      S("4. Records", "٤. السجلات",
        "Grease-trap cleaning log, tanker/disposal manifests, drain maintenance records.",
        "سجل تنظيف مصائد الدهون، مستندات الصهاريج/التخلص، سجلات صيانة المصارف."),
      S("5. Frequency", "٥. التكرار",
        "Grease-trap cleaning per schedule; drain checks weekly.",
        "تنظيف مصائد الدهون حسب الجدول؛ فحص المصارف أسبوعياً."),
    ],
  }),
  sop("en", 3, {
    title: "Refrigerant Gas Management & Disposal",
    titleAr: "إدارة غازات التبريد والتخلص منها",
    subtitle: "Leak prevention, certified handling, logging & compliant disposal",
    subtitleAr: "منع التسرّب، مناولة معتمدة، تسجيل، وتخلص متوافق",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Minimise refrigerant emissions and manage handling, top-up and disposal in an environmentally compliant way.",
        "تقليل انبعاثات غازات التبريد وإدارة المناولة والتعبئة والتخلص بشكل متوافق بيئياً."),
      S("2. Scope", "٢. النطاق",
        "All refrigeration systems, refrigerant handling, recovery and disposal.",
        "كل أنظمة التبريد ومناولة الغاز واستعادته والتخلص منه."),
      S("3. Procedure", "٣. الإجراء",
        "1) Only certified technicians handle, charge or recover refrigerant.\n2) Routine leak detection and prompt repair of any leak.\n3) Record all top-ups, recovery and quantities per system.\n4) Recover refrigerant into approved cylinders — never vent to atmosphere.\n5) Dispose of / return used refrigerant via licensed channels; keep certificates.",
        "١) لا يناول أو يشحن أو يستعيد الغاز إلا فنيون معتمدون.\n٢) كشف تسرّب دوري وإصلاح فوري لأي تسرّب.\n٣) تسجيل كل عمليات التعبئة والاستعادة والكميات لكل نظام.\n٤) استعادة الغاز في أسطوانات معتمدة — ممنوع التنفيس للجو.\n٥) التخلص/الإرجاع للغاز المستعمل عبر قنوات مرخّصة؛ الاحتفاظ بالشهادات."),
      S("4. Records", "٤. السجلات",
        "Refrigerant log (top-up/recovery), technician certifications, leak-repair records, disposal certificates.",
        "سجل غاز التبريد (تعبئة/استعادة)، شهادات الفنيين، سجلات إصلاح التسرّب، شهادات التخلص."),
      S("5. Frequency", "٥. التكرار",
        "Leak detection per schedule; logging on every event.",
        "كشف التسرّب حسب الجدول؛ التسجيل عند كل حدث."),
    ],
  }),
  sop("en", 4, {
    title: "Energy & Water Consumption Monitoring",
    titleAr: "مراقبة استهلاك الطاقة والمياه",
    subtitle: "Meter readings, targets, leak detection & efficiency actions",
    subtitleAr: "قراءات العدادات، الأهداف، كشف التسرّب، وإجراءات الكفاءة",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Reduce energy and water consumption and cost, and detect abnormal usage (leaks/faults) early.",
        "خفض استهلاك وتكلفة الطاقة والمياه، وكشف الاستهلاك غير الطبيعي (التسرّبات/الأعطال) مبكراً."),
      S("2. Scope", "٢. النطاق",
        "Electricity, water and (where applicable) fuel consumption across the site.",
        "استهلاك الكهرباء والمياه و(حيثما ينطبق) الوقود في كامل الموقع."),
      S("3. Procedure", "٣. الإجراء",
        "1) Read meters on schedule and log consumption.\n2) Compare against targets/baselines; investigate abnormal spikes.\n3) Detect and repair water leaks and inefficient equipment.\n4) Apply efficiency measures (door discipline, lighting, maintenance of refrigeration).\n5) Report trends to management and set improvement actions.",
        "١) قراءة العدادات حسب الجدول وتسجيل الاستهلاك.\n٢) المقارنة بالأهداف/القيم المرجعية؛ التحقيق في الارتفاعات غير الطبيعية.\n٣) كشف وإصلاح تسرّبات المياه والمعدات غير الكفؤة.\n٤) تطبيق إجراءات الكفاءة (انضباط الأبواب، الإضاءة، صيانة التبريد).\n٥) رفع الاتجاهات للإدارة ووضع إجراءات تحسين."),
      S("4. Records", "٤. السجلات",
        "Meter reading logs, consumption trend reports, leak/repair records, improvement action list.",
        "سجلات قراءة العدادات، تقارير اتجاه الاستهلاك، سجلات التسرّب/الإصلاح، قائمة إجراءات التحسين."),
      S("5. Frequency", "٥. التكرار",
        "Meter readings weekly/monthly; trend review monthly.",
        "قراءة العدادات أسبوعياً/شهرياً؛ مراجعة الاتجاهات شهرياً."),
    ],
  }),

  // ══════════════════════════════════════════════════════════════════════
  // ADMINISTRATIVE
  // ══════════════════════════════════════════════════════════════════════
  sop("ad", 1, {
    title: "Annual HSE Document Review",
    titleAr: "مراجعة وثائق HSE السنوية",
    subtitle: "Controlled review, version control, approval & distribution",
    subtitleAr: "مراجعة محكومة، ضبط الإصدارات، الاعتماد، والتوزيع",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Keep all HSE policies, SOPs and forms current, controlled and approved.",
        "إبقاء كل سياسات وإجراءات ونماذج HSE محدَّثة ومحكومة ومعتمدة."),
      S("2. Scope", "٢. النطاق",
        "All controlled HSE documents: policies, SOPs, forms, plans and registers.",
        "كل وثائق HSE المحكومة: السياسات والإجراءات والنماذج والخطط والسجلات."),
      S("3. Procedure", "٣. الإجراء",
        "1) Review each document at least annually or after any significant change/incident.\n2) Update content, revision number, dates and approvals.\n3) Approve via the authorised signatory before release.\n4) Distribute the current version; withdraw superseded copies.\n5) Log the change in the change-management/document register.",
        "١) مراجعة كل وثيقة سنوياً على الأقل أو بعد أي تغيير جوهري/حادث.\n٢) تحديث المحتوى ورقم الإصدار والتواريخ والاعتمادات.\n٣) الاعتماد عبر المخوّل بالتوقيع قبل الإصدار.\n٤) توزيع النسخة الحالية؛ سحب النسخ المُستبدَلة.\n٥) تسجيل التغيير في سجل إدارة التغيير/الوثائق."),
      S("4. Records", "٤. السجلات",
        "Document register, revision history, approval signatures, distribution list.",
        "سجل الوثائق، تاريخ الإصدارات، توقيعات الاعتماد، قائمة التوزيع."),
      S("5. Frequency", "٥. التكرار",
        "Annually or on significant change.",
        "سنوياً أو عند تغيير جوهري."),
    ],
  }),
  sop("ad", 2, {
    title: "HSE Internal Audit",
    titleAr: "التدقيق الداخلي",
    subtitle: "Planned audits, findings, corrective actions & follow-up",
    subtitleAr: "تدقيق مخطّط، ملاحظات، إجراءات تصحيحية، ومتابعة",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Verify the HSE management system is implemented, effective and compliant, and drive continual improvement.",
        "التحقق من تطبيق نظام إدارة HSE وفعاليته وامتثاله، ودفع التحسين المستمر."),
      S("2. Scope", "٢. النطاق",
        "All HSE processes, areas and requirements across the site.",
        "كل عمليات ومناطق ومتطلبات HSE في الموقع."),
      S("3. Procedure", "٣. الإجراء",
        "1) Prepare an annual audit programme covering all areas.\n2) Use trained, independent auditors and an approved checklist.\n3) Record findings (conformity / non-conformity / observation) with evidence.\n4) Raise corrective actions with owners and due dates.\n5) Verify closure and effectiveness; feed results into management review.",
        "١) إعداد برنامج تدقيق سنوي يغطي كل المناطق.\n٢) استخدام مدققين مدرَّبين مستقلين وقائمة مراجعة معتمدة.\n٣) تسجيل الملاحظات (مطابقة / عدم مطابقة / ملاحظة) مع الأدلة.\n٤) فتح إجراءات تصحيحية مع المسؤولين والمواعيد.\n٥) التحقق من الإغلاق والفعالية؛ إدخال النتائج في مراجعة الإدارة."),
      S("4. Records", "٤. السجلات",
        "Audit programme & plan, audit reports, non-conformance & CAPA records, follow-up log.",
        "برنامج وخطة التدقيق، تقارير التدقيق، سجلات عدم المطابقة و CAPA، سجل المتابعة."),
      S("5. Frequency", "٥. التكرار",
        "Per annual programme; follow-up until closure.",
        "حسب البرنامج السنوي؛ المتابعة حتى الإغلاق."),
    ],
  }),
  sop("ad", 3, {
    title: "Government Inspector Reception",
    titleAr: "استقبال مفتشي الجهات الحكومية",
    subtitle: "Verify ID, escort, cooperate, record & follow up on findings",
    subtitleAr: "التحقق من الهوية، المرافقة، التعاون، التوثيق، ومتابعة الملاحظات",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Ensure professional, compliant handling of visits by municipality, MOHRE, Civil Defence and other authorities.",
        "ضمان تعامل مهني ومتوافق مع زيارات البلدية ووزارة الموارد البشرية والدفاع المدني والجهات الأخرى."),
      S("2. Scope", "٢. النطاق",
        "All official/regulatory inspection visits to the facility.",
        "كل الزيارات التفتيشية الرسمية/الرقابية للمنشأة."),
      S("3. Procedure", "٣. الإجراء",
        "1) Verify the inspector's ID and authority; notify management/QA/HSE immediately.\n2) Provide required PPE and brief on safety before entry.\n3) Accompany the inspector at all times; cooperate and provide requested records.\n4) Record the visit scope, observations and any instructions given.\n5) Raise corrective actions for any findings and track to closure.\n6) File the inspection report and any issued notices.",
        "١) التحقق من هوية المفتش وصلاحيته؛ إبلاغ الإدارة/الجودة/HSE فوراً.\n٢) توفير معدات الوقاية المطلوبة والإحاطة بالسلامة قبل الدخول.\n٣) مرافقة المفتش طوال الوقت؛ التعاون وتقديم السجلات المطلوبة.\n٤) توثيق نطاق الزيارة والملاحظات وأي تعليمات صدرت.\n٥) فتح إجراءات تصحيحية لأي ملاحظات ومتابعتها حتى الإغلاق.\n٦) حفظ تقرير التفتيش وأي إخطارات صادرة."),
      S("4. Records", "٤. السجلات",
        "Visitor/inspection log, inspector reports & notices, corrective-action records, closure evidence.",
        "سجل الزوار/التفتيش، تقارير وإخطارات المفتش، سجلات الإجراءات التصحيحية، أدلة الإغلاق."),
      S("5. Frequency", "٥. التكرار",
        "On each inspection visit.",
        "عند كل زيارة تفتيشية."),
    ],
  }),
  sop("ad", 4, {
    title: "Contractor & Supplier HSE Management",
    titleAr: "إدارة المقاولين والموردين",
    subtitle: "Pre-qualification, induction, permit control & performance review",
    subtitleAr: "التأهيل المسبق، التعريف، ضبط التصاريح، ومراجعة الأداء",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Ensure contractors and suppliers meet HSE requirements and work safely on site.",
        "ضمان استيفاء المقاولين والموردين لمتطلبات HSE والعمل بأمان في الموقع."),
      S("2. Scope", "٢. النطاق",
        "All contractors, service providers and suppliers performing work or deliveries on site.",
        "كل المقاولين ومقدمي الخدمات والموردين الذين ينفّذون أعمالاً أو توريدات في الموقع."),
      S("3. Procedure", "٣. الإجراء",
        "1) Pre-qualify contractors on HSE (documents, insurance, competencies).\n2) HSE induction and site rules before any work.\n3) Control high-risk work via the permit system (SOP-OHS-07) and method statements/risk assessments.\n4) Supervise and monitor contractor compliance during work.\n5) Review contractor/supplier HSE performance and record incidents.",
        "١) تأهيل المقاولين مسبقاً في HSE (الوثائق، التأمين، الكفاءات).\n٢) تعريف HSE وقواعد الموقع قبل أي عمل.\n٣) ضبط الأعمال عالية الخطورة عبر نظام التصاريح (SOP-OHS-07) وبيانات الطريقة/تقييم المخاطر.\n٤) الإشراف ومراقبة امتثال المقاول أثناء العمل.\n٥) مراجعة أداء HSE للمقاول/المورد وتسجيل الحوادث."),
      S("4. Records", "٤. السجلات",
        "Contractor pre-qualification records, induction records, permits, performance-review reports.",
        "سجلات التأهيل المسبق للمقاول، سجلات التعريف، التصاريح، تقارير مراجعة الأداء."),
      S("5. Frequency", "٥. التكرار",
        "On engagement + per job; performance review periodically.",
        "عند التعاقد + لكل مهمة؛ مراجعة الأداء دورياً."),
    ],
  }),
  sop("ad", 5, {
    title: "Management of Change (MOC)",
    titleAr: "إدارة التغيير",
    subtitle: "Assess, approve, implement & verify changes before roll-out",
    subtitleAr: "تقييم واعتماد وتنفيذ والتحقق من التغييرات قبل التطبيق",
    sections: [
      S("1. Purpose", "١. الغرض",
        "Ensure changes to processes, equipment, materials or personnel are assessed for HSE impact and controlled before implementation.",
        "ضمان تقييم التغييرات في العمليات أو المعدات أو المواد أو الأفراد من حيث أثرها على HSE والتحكم بها قبل التنفيذ."),
      S("2. Scope", "٢. النطاق",
        "Any permanent or temporary change affecting food safety, occupational safety or the environment.",
        "أي تغيير دائم أو مؤقت يؤثر على سلامة الغذاء أو السلامة المهنية أو البيئة."),
      S("3. Procedure", "٣. الإجراء",
        "1) Raise a change request describing the change and reason.\n2) Assess HSE risks and impact on existing controls/documents.\n3) Approve via the authorised level before implementation.\n4) Update affected SOPs, risk assessments and training.\n5) Implement, communicate and train affected staff.\n6) Verify effectiveness and record in the change-management log.",
        "١) رفع طلب تغيير يصف التغيير وسببه.\n٢) تقييم مخاطر HSE والأثر على الضوابط/الوثائق الحالية.\n٣) الاعتماد من المستوى المخوّل قبل التنفيذ.\n٤) تحديث الإجراءات وتقييمات المخاطر والتدريب المتأثرة.\n٥) التنفيذ والتواصل وتدريب الموظفين المتأثرين.\n٦) التحقق من الفعالية والتسجيل في سجل إدارة التغيير."),
      S("4. Records", "٤. السجلات",
        "Change request & approval, risk assessment, updated documents, training records, change-management log.",
        "طلب التغيير والاعتماد، تقييم المخاطر، الوثائق المحدَّثة، سجلات التدريب، سجل إدارة التغيير."),
      S("5. Frequency", "٥. التكرار",
        "On every change.",
        "عند كل تغيير."),
    ],
  }),
];

// Grouped view for section rendering.
export const hseSopGroups = Object.values(SOP_GROUP_META).map((meta) => ({
  ...meta,
  items: hseSops.filter((s) => s.group === meta.key),
}));

export default hseSops;
