// src/pages/sweets-training/content/quizB.js
// Trainee quiz bank, part B (modules 8–13). Same shape as quizA.js.
const q = (difficulty, q_en, q_ar, options_en, options_ar, correct) =>
  ({ difficulty, q_en, q_ar, options_en, options_ar, correct });
const E = "Easy", M = "Medium", H = "Hard";

export const QUIZ_B = {
  "Cleaning & Sanitation": [
    q(E, "Which comes first?", "أيهما أولاً؟",
      ["Cleaning", "Sanitising", "Drying"], ["التنظيف", "التعقيم", "التجفيف"], 0),
    q(E, "Does a sanitiser work on a dirty surface?", "هل يعمل المعقم على سطح متسخ؟",
      ["Yes, better", "No — clean it first", "Only on stainless steel"], ["نعم وبشكل أفضل", "لا — نظّفه أولاً", "على الستانلس فقط"], 1),
    q(E, "Chemicals are kept:", "المواد الكيميائية تُحفظ:",
      ["In drink bottles", "Next to the sugar", "In original labelled containers, away from food"], ["في عبوات المشروبات", "بجانب السكر", "في عبواتها الأصلية المعنونة بعيداً عن الغذاء"], 2),
    q(E, "A spill of cream on the floor is cleaned:", "انسكاب الكريمة على الأرض يُنظف:",
      ["Immediately", "At the end of the day", "By the next shift"], ["فوراً", "في نهاية اليوم", "من الوردية التالية"], 0),
    q(E, "Who signs the daily cleanliness sheet?", "من يوقع ورقة النظافة اليومية؟",
      ["Anyone later", "The person who cleaned", "Nobody"], ["أي شخص لاحقاً", "الشخص الذي نظّف", "لا أحد"], 1),
    q(M, "Chlorine on food-contact surfaces should be:", "الكلور على أسطح ملامسة الغذاء يجب أن يكون:",
      ["1000 ppm", "5 ppm", "50–200 ppm"], ["1000 جزء بالمليون", "5 أجزاء بالمليون", "50–200 جزء بالمليون"], 2),
    q(M, "How is sanitiser strength checked?", "كيف يُفحص تركيز المعقم؟",
      ["With a test strip", "By smell", "By colour"], ["بشريط الفحص", "بالرائحة", "باللون"], 0),
    q(M, "The QAC reading is 600 ppm. You:", "قراءة الأمونيوم الرباعي 600 جزء بالمليون. أنت:",
      ["Use it — stronger is better", "Re-mix and re-test, then record", "Add chlorine"], ["تستعمله — الأقوى أفضل", "تعيد الخلط والفحص ثم تسجل", "تضيف الكلور"], 1),
    q(M, "Why dismantle the mixer beater and guard for cleaning?", "لماذا يُفك مضرب الخلاط وغطاؤه عند التنظيف؟",
      ["It is faster", "To oil them", "Sugar and cream residues in joints feed bacteria"], ["أسرع", "لتزييتها", "بقايا السكر والكريمة في المفاصل تغذي البكتيريا"], 2),
    q(M, "Sanitised surfaces are dried by:", "الأسطح المعقمة تُجفف:",
      ["Air-drying", "A used cloth", "The apron"], ["بالتجفيف الهوائي", "بفوطة مستعملة", "بالمريول"], 0),
    q(H, "Peracetic acid range for surfaces is:", "مدى حمض البيروكسي أسيتيك للأسطح:",
      ["10–20 ppm", "150–300 ppm", "2000 ppm"], ["10–20 جزء بالمليون", "150–300 جزء بالمليون", "2000 جزء بالمليون"], 1),
    q(H, "Mixing chlorine with an acid cleaner can:", "خلط الكلور بمنظف حمضي قد:",
      ["Clean better", "Do nothing", "Release toxic chlorine gas"], ["ينظف أفضل", "لا يفعل شيئاً", "يطلق غاز كلور سام"], 2),
    q(H, "Where is information on a chemical's hazards and first aid?", "أين معلومات مخاطر المادة الكيميائية وإسعافاتها؟",
      ["In its Safety Data Sheet (SDS)", "On the price label", "In the recipe book"], ["في نشرة بيانات السلامة (SDS)", "على ملصق السعر", "في كتاب الوصفات"], 0),
    q(H, "Correct order of cleaning steps:", "الترتيب الصحيح لخطوات التنظيف:",
      ["Sanitise → wash → rinse", "Remove debris → wash → rinse → sanitise → air-dry", "Rinse → dry → wash"], ["تعقيم ← غسل ← شطف", "إزالة البقايا ← غسل ← شطف ← تعقيم ← تجفيف هوائي", "شطف ← تجفيف ← غسل"], 1),
    q(H, "Why must sanitiser have its contact time?", "لماذا يجب أن يأخذ المعقم زمن التماس؟",
      ["To dry the table", "For the smell", "It needs time on the surface to kill bacteria"], ["لتجفيف الطاولة", "للرائحة", "يحتاج وقتاً على السطح ليقتل البكتيريا"], 2),
  ],

  "Foreign Body & Cross-Contamination": [
    q(E, "Flour, sugar and cocoa are ___ before use.", "الطحين والسكر والكاكاو ___ قبل الاستعمال.",
      ["Sieved", "Washed", "Heated"], ["تُنخل", "تُغسل", "تُسخن"], 0),
    q(E, "Is glass allowed in production?", "هل الزجاج مسموح في الإنتاج؟",
      ["Yes", "No", "Only jars"], ["نعم", "لا", "المرطبانات فقط"], 1),
    q(E, "Where are staples and strings removed from packs?", "أين تُزال الدبابيس والخيوط من العبوات؟",
      ["On the work table", "Inside the mixer", "Outside the production area"], ["على طاولة العمل", "داخل الخلاط", "خارج منطقة الإنتاج"], 2),
    q(E, "Finished products are kept:", "المنتجات النهائية تُحفظ:",
      ["Covered", "Open", "Next to raw eggs"], ["مغطاة", "مكشوفة", "بجانب البيض النيء"], 0),
    q(E, "You find a piece of wire in a cake. First you:", "وجدت قطعة سلك في كيك. أولاً:",
      ["Throw it away quietly", "Stop, keep it, tell the supervisor", "Continue working"], ["ترميه بهدوء", "تتوقف وتحتفظ به وتبلغ المشرف", "تكمل العمل"], 1),
    q(M, "Whisks and beaters are checked for broken wires:", "المضارب تُفحص للأسلاك المكسورة:",
      ["Once a year", "Never", "Before and after use"], ["مرة سنوياً", "أبداً", "قبل وبعد الاستعمال"], 2),
    q(M, "A glass breaks near the cream room. The area is:", "انكسر زجاج قرب غرفة الكريمة. المنطقة:",
      ["Quarantined and the supervisor told", "Swept and work continues", "Ignored if pieces are small"], ["تُعزل ويُبلغ المشرف", "تُكنس ويستمر العمل", "تُتجاهل إذا كانت القطع صغيرة"], 0),
    q(M, "Colour-coded boards and utensils help to:", "الألواح والأدوات الملونة تساعد على:",
      ["Look nice", "Prevent cross-contamination", "Save money"], ["المظهر الجميل", "منع التلوث التبادلي", "توفير المال"], 1),
    q(M, "Which is a physical hazard in dried fruit?", "أي مما يلي خطر فيزيائي في الفواكه المجففة؟",
      ["Sugar", "Moisture", "Stones"], ["السكر", "الرطوبة", "الحصى"], 2),
    q(M, "Raw eggs are stored:", "البيض النيء يُخزن:",
      ["Away from and below finished products", "Above the cakes", "On the decorating table"], ["بعيداً عن المنتجات النهائية وتحتها", "فوق الكيك", "على طاولة التزيين"], 0),
    q(H, "After a foreign body is found, the batch is:", "بعد وجود جسم غريب، الدفعة:",
      ["Sold quickly", "Held until the supervisor decides and records", "Mixed with a good batch"], ["تُباع بسرعة", "تُوقف حتى يقرر المشرف ويسجل", "تُخلط بدفعة سليمة"], 1),
    q(H, "Why are separate cloths used for surfaces and equipment?", "لماذا تُستعمل فوط منفصلة للأسطح والمعدات؟",
      ["Cloths are cheap", "To dry faster", "A cloth carries dirt and bacteria from one to the other"], ["الفوط رخيصة", "لتجفيف أسرع", "الفوطة تنقل الأوساخ والبكتيريا من مكان لآخر"], 2),
    q(H, "A broken piece of a hard-plastic decoration tool is missing. You:", "قطعة من أداة تزيين بلاستيكية صلبة مفقودة. أنت:",
      ["Report it; products since the last check are held", "Buy a new tool", "Nothing if it is small"], ["تبلغ؛ وتُوقف المنتجات منذ آخر فحص", "تشتري أداة جديدة", "لا شيء إذا كانت صغيرة"], 0),
    q(H, "Which record is used when a foreign body is confirmed?", "أي سجل يُستعمل عند تأكيد وجود جسم غريب؟",
      ["The cleaning sheet", "A non-conformance report", "The attendance sheet"], ["ورقة التنظيف", "تقرير عدم المطابقة", "كشف الحضور"], 1),
    q(H, "Nut shells in a pistachio lot are a hazard of type:", "قشور المكسرات في دفعة فستق خطر من النوع:",
      ["Chemical", "Biological", "Physical"], ["كيميائي", "حيوي", "فيزيائي"], 2),
  ],

  "Pest Control Awareness": [
    q(E, "Which pests are attracted to flour and nuts?", "أي آفات تنجذب للطحين والمكسرات؟",
      ["Stored-product insects (beetles, moths)", "Fish", "Birds only"], ["حشرات المواد المخزنة (خنافس، عث)", "الأسماك", "الطيور فقط"], 0),
    q(E, "You see droppings in the dry store. You:", "رأيت فضلات في المخزن الجاف. أنت:",
      ["Clean them and say nothing", "Report to the supervisor immediately", "Wait a week"], ["تنظفها ولا تقول شيئاً", "تبلغ المشرف فوراً", "تنتظر أسبوعاً"], 1),
    q(E, "Doors to the outside should be:", "الأبواب للخارج يجب أن تكون:",
      ["Open for air", "Propped with a box", "Closed"], ["مفتوحة للتهوية", "مسنودة بكرتونة", "مغلقة"], 2),
    q(E, "Waste bins should be:", "سلال النفايات يجب أن تكون:",
      ["Closed and emptied regularly", "Open", "Full before emptying"], ["مغلقة وتُفرّغ بانتظام", "مفتوحة", "ممتلئة قبل التفريغ"], 0),
    q(E, "Can you use your own insect spray in food areas?", "هل تستعمل رشاشاً خاصاً للحشرات في مناطق الغذاء؟",
      ["Yes", "No — only the licensed contractor", "Yes, at night"], ["نعم", "لا — المقاول المرخص فقط", "نعم ليلاً"], 1),
    q(M, "Webbing in a flour sack is a sign of:", "الخيوط في كيس الطحين علامة على:",
      ["Good quality", "Humidity only", "Moth infestation"], ["جودة عالية", "رطوبة فقط", "إصابة بالعث"], 2),
    q(M, "Bait stations should be:", "محطات الطعم يجب أن:",
      ["Left where the contractor placed them", "Moved to clean", "Removed during audits"], ["تُترك حيث وضعها المقاول", "تُنقل للتنظيف", "تُزال أثناء التدقيق"], 0),
    q(M, "Why does FEFO help pest control?", "كيف يساعد FEFO في مكافحة الآفات؟",
      ["It makes packs heavier", "Stock doesn't sit long enough to be infested", "Pests dislike new packs"], ["يجعل العبوات أثقل", "لا يبقى المخزون مدة كافية لإصابته", "الآفات لا تحب العبوات الجديدة"], 1),
    q(M, "Sugar spills mostly attract:", "انسكاب السكر يجذب غالباً:",
      ["Rodents only", "Birds", "Ants and wasps"], ["القوارض فقط", "الطيور", "النمل والدبابير"], 2),
    q(M, "Grease marks along the bottom of walls may indicate:", "آثار الدهون أسفل الجدران قد تدل على:",
      ["Rodent runways", "Good cleaning", "Water leaks only"], ["ممرات القوارض", "تنظيف جيد", "تسرب مياه فقط"], 0),
    q(H, "A pack of cocoa has live insects. Besides rejecting it you should:", "عبوة كاكاو فيها حشرات حية. بالإضافة لرفضها يجب:",
      ["Use the rest of the lot", "Check the whole lot and nearby stock", "Freeze it and use it"], ["استعمال بقية الدفعة", "فحص الدفعة كلها والمخزون المجاور", "تجميدها واستعمالها"], 1),
    q(H, "Why are insect-killer units not placed directly above work tables?", "لماذا لا توضع أجهزة قتل الحشرات فوق طاولات العمل مباشرة؟",
      ["They are too bright", "They are noisy", "Dead insects can fall onto food"], ["شديدة الإضاءة", "مزعجة", "قد تسقط الحشرات الميتة على الطعام"], 2),
    q(H, "Strip curtains and fly screens are part of:", "الستائر البلاستيكية وشبك الذباب جزء من:",
      ["Pest proofing (prevention)", "Decoration", "Cleaning chemicals"], ["منع دخول الآفات (الوقاية)", "الديكور", "مواد التنظيف"], 0),
    q(H, "Who records pest activity and treatments?", "من يسجل نشاط الآفات والمعالجات؟",
      ["Nobody", "The contractor, with a copy in the pest control record", "The customer"], ["لا أحد", "المقاول مع نسخة في سجل مكافحة الآفات", "الزبون"], 1),
    q(H, "Birds nesting near the loading bay are a risk because:", "تعشيش الطيور قرب منطقة التحميل خطر لأن:",
      ["They are noisy", "They eat waste only", "Droppings and feathers can contaminate products"], ["مزعجة", "تأكل النفايات فقط", "الفضلات والريش قد تلوث المنتجات"], 2),
  ],

  "Labelling, Shelf Life & Traceability": [
    q(E, "Which date is about SAFETY?", "أي تاريخ يتعلق بالسلامة؟",
      ["Use-by", "Best-before", "Packing date"], ["يُستهلك قبل", "يُفضّل قبل", "تاريخ التعبئة"], 0),
    q(E, "Can you change the date on a label?", "هل يمكنك تغيير التاريخ على البطاقة؟",
      ["Yes, if the product looks fine", "No, never", "Yes, by one day"], ["نعم إذا بدا المنتج جيداً", "لا أبداً", "نعم بيوم واحد"], 1),
    q(E, "Allergens on a label must be:", "مسببات الحساسية على البطاقة يجب أن:",
      ["Hidden", "Optional", "Clearly declared"], ["تُخفى", "اختيارية", "تُذكر بوضوح"], 2),
    q(E, "Ingredients on a label are listed in:", "المكونات على البطاقة تُذكر:",
      ["Descending order by quantity", "Alphabetical order", "Any order"], ["بترتيب تنازلي حسب الكمية", "بترتيب أبجدي", "بأي ترتيب"], 0),
    q(E, "Which product usually carries a use-by date?", "أي منتج يحمل عادة تاريخ 'يُستهلك قبل'؟",
      ["Dry biscuits", "Cream cake", "Sugar"], ["البسكويت الجاف", "كيك الكريمة", "السكر"], 1),
    q(M, "Who sets a product's shelf life?", "من يحدد مدة صلاحية المنتج؟",
      ["The worker packing it", "The customer", "The approved product list"], ["العامل الذي يعبئه", "الزبون", "قائمة المنتجات المعتمدة"], 2),
    q(M, "Traceability means one step back and one step:", "التتبع يعني خطوة للخلف وخطوة:",
      ["Forward", "Sideways", "Up"], ["للأمام", "للجانب", "للأعلى"], 0),
    q(M, "Where are the raw lots used in a batch recorded?", "أين تُسجل دفعات المواد الخام المستعملة في تشغيلة؟",
      ["Nowhere", "In the production log", "On the wall"], ["لا مكان", "في سجل الإنتاج", "على الجدار"], 1),
    q(M, "Putting a new label over an old one is:", "وضع ملصق جديد فوق قديم:",
      ["Allowed for speed", "Allowed at weekends", "Not allowed"], ["مسموح للسرعة", "مسموح في العطل", "غير مسموح"], 2),
    q(M, "What does the batch/lot number allow?", "ماذا يتيح رقم الدفعة؟",
      ["Finding every affected product in a recall", "A cheaper price", "Nothing"], ["إيجاد كل منتج متأثر عند السحب", "سعراً أرخص", "لا شيء"], 0),
    q(H, "Which GSO standard covers labelling of prepackaged foods?", "أي مواصفة خليجية تخص بطاقات الأغذية المعبأة؟",
      ["GSO 150", "GSO 9", "ISO 22000"], ["GSO 150", "GSO 9", "ISO 22000"], 1),
    q(H, "Which GSO standard covers expiration periods?", "أي مواصفة خليجية تخص فترات الصلاحية؟",
      ["GSO 9", "CXC 80", "GSO 150"], ["GSO 9", "CXC 80", "GSO 150"], 2),
    q(H, "A supplier recalls a milk powder lot. With good records you can:", "المورد يسحب دفعة حليب بودرة. بسجلات جيدة يمكنك:",
      ["Find which batches used it and where they were sent", "Only stop buying it", "Nothing"], ["معرفة التشغيلات التي استعملتها وإلى أين أُرسلت", "التوقف عن شرائها فقط", "لا شيء"], 0),
    q(H, "Best-before has passed on a sealed pack of biscuits. It:", "انتهى 'يُفضّل قبل' على عبوة بسكويت مغلقة. هي:",
      ["Can be relabelled with a new date", "Is not used or sold under company rules", "Is sold at double price"], ["يُعاد وسمها بتاريخ جديد", "لا تُستعمل ولا تُباع وفق قواعد الشركة", "تُباع بضعف السعر"], 1),
    q(H, "The dispatch record must show:", "سجل الإرسال يجب أن يبيّن:",
      ["The driver's age", "The weather", "Where each quantity went, when, and how much"], ["عمر السائق", "الطقس", "أين ذهبت كل كمية ومتى وكم"], 2),
  ],

  "HACCP Basics for Confectionery": [
    q(E, "HACCP stands for:", "HACCP تعني:",
      ["Hazard Analysis and Critical Control Points", "Health And Cleaning Control Plan", "Hot And Cold Cooking Process"], ["تحليل المخاطر ونقاط التحكم الحرجة", "خطة التحكم بالصحة والتنظيف", "عملية الطبخ الساخن والبارد"], 0),
    q(E, "How many HACCP principles are there?", "كم عدد مبادئ الهاسب؟",
      ["3", "7", "12"], ["3", "7", "12"], 1),
    q(E, "When should records be filled in?", "متى تُعبأ السجلات؟",
      ["At the end of the week", "In advance", "At the time of the check"], ["في نهاية الأسبوع", "مسبقاً", "وقت الفحص"], 2),
    q(E, "Salmonella from eggs is a hazard of type:", "السالمونيلا من البيض خطر من النوع:",
      ["Biological", "Physical", "Chemical"], ["حيوي", "فيزيائي", "كيميائي"], 0),
    q(E, "Metal from a broken whisk is a hazard of type:", "المعدن من مضرب مكسور خطر من النوع:",
      ["Biological", "Physical", "Allergen"], ["حيوي", "فيزيائي", "مسبب حساسية"], 1),
    q(M, "The critical limit for cooking custard here is:", "الحد الحرج لطبخ الكاسترد هنا:",
      ["50 °C", "63 °C at the surface", "Core ≥ 75 °C"], ["50 °م", "63 °م على السطح", "القلب 75 °م أو أكثر"], 2),
    q(M, "What is a corrective action?", "ما هو الإجراء التصحيحي؟",
      ["What you do when a limit is not met", "A new recipe", "A cleaning schedule"], ["ما تفعله عند عدم تحقق الحد", "وصفة جديدة", "جدول تنظيف"], 0),
    q(M, "Which is a chemical hazard in confectionery?", "أي مما يلي خطر كيميائي في الحلويات؟",
      ["Hair", "Aflatoxin in nuts", "Salmonella"], ["الشعر", "الأفلاتوكسين في المكسرات", "السالمونيلا"], 1),
    q(M, "Chilled storage and display critical limit:", "الحد الحرج للحفظ والعرض المبرّد:",
      ["≤ 15 °C", "≤ 10 °C", "≤ 5 °C"], ["15 °م أو أقل", "10 °م أو أقل", "5 °م أو أقل"], 2),
    q(M, "Checking that the HACCP plan works (e.g. reviewing records) is called:", "التأكد من أن خطة الهاسب تعمل (مثل مراجعة السجلات) يُسمى:",
      ["Verification", "Monitoring", "Receiving"], ["التحقق", "المراقبة", "الاستلام"], 0),
    q(H, "What is the first HACCP principle?", "ما هو المبدأ الأول للهاسب؟",
      ["Keep records", "Conduct a hazard analysis", "Set corrective actions"], ["حفظ السجلات", "إجراء تحليل المخاطر", "وضع الإجراءات التصحيحية"], 1),
    q(H, "A cooling record shows 30 °C at 2 hours. This is:", "سجل التبريد يُظهر 30 °م بعد ساعتين. هذا:",
      ["Within the limit", "Acceptable in summer", "A deviation needing corrective action"], ["ضمن الحد", "مقبول في الصيف", "انحراف يحتاج إجراءً تصحيحياً"], 2),
    q(H, "Why is an allergen changeover treated as a control point?", "لماذا يُعامل تبديل مسببات الحساسية كنقطة تحكم؟",
      ["Because traces can harm allergic customers and cooking won't remove them", "It takes a long time", "Because it is cheap"], ["لأن الآثار قد تؤذي الزبون المتحسس والطبخ لا يزيلها", "يأخذ وقتاً طويلاً", "لأنه رخيص"], 0),
    q(H, "Filling a temperature record at the end of the day from memory is:", "تعبئة سجل الحرارة في نهاية اليوم من الذاكرة:",
      ["Fine if the numbers are normal", "Falsifying the record", "Recommended"], ["مقبول إذا كانت الأرقام طبيعية", "تزوير للسجل", "مستحسن"], 1),
    q(H, "Which standard specifies food safety management systems?", "أي مواصفة تحدد أنظمة إدارة سلامة الغذاء؟",
      ["ISO 9001", "GSO 9", "ISO 22000:2018"], ["ISO 9001", "GSO 9", "ISO 22000:2018"], 2),
  ],

  "OHS: Ovens, Burns & Hot Sugar": [
    q(E, "Oven gloves must be:", "قفازات الفرن يجب أن تكون:",
      ["Dry", "Wet", "Any gloves"], ["جافة", "مبللة", "أي قفازات"], 0),
    q(E, "How long do you cool a burn under running water?", "كم تبرّد الحرق تحت الماء الجاري؟",
      ["10 seconds", "At least 20 minutes", "No water"], ["10 ثوانٍ", "20 دقيقة على الأقل", "بدون ماء"], 1),
    q(E, "What do you NOT put on a burn?", "ماذا لا تضع على الحرق؟",
      ["Cool running water", "A clean non-stick dressing", "Butter or toothpaste"], ["ماء جارٍ بارد", "ضماد نظيف غير لاصق", "زبدة أو معجون أسنان"], 2),
    q(E, "When passing behind someone with a hot tray you say:", "عند المرور خلف شخص بصينية ساخنة تقول:",
      ["\"Hot behind\"", "Nothing", "\"Excuse me\" after passing"], ["\"ساخن خلفك\"", "لا شيء", "\"عذراً\" بعد المرور"], 0),
    q(E, "Every burn must be:", "كل حرق يجب أن:",
      ["Kept secret", "Reported and recorded", "Treated at home"], ["يُكتم", "يُبلَّغ عنه ويُسجَّل", "يُعالج في البيت"], 1),
    q(M, "Why are wet oven gloves dangerous?", "لماذا قفازات الفرن المبللة خطرة؟",
      ["They slip", "They shrink", "Water conducts heat to the hand"], ["تنزلق", "تنكمش", "الماء ينقل الحرارة إلى اليد"], 2),
    q(M, "Why is hot sugar/caramel especially dangerous?", "لماذا السكر الساخن/الكراميل خطر بشكل خاص؟",
      ["It is much hotter than boiling water and sticks to skin", "It is sweet", "It cools instantly"], ["أسخن بكثير من الماء المغلي ويلتصق بالجلد", "لأنه حلو", "يبرد فوراً"], 0),
    q(M, "Open an oven door:", "افتح باب الفرن:",
      ["Face first to look inside", "Away from your face, letting steam escape", "Quickly and lean in"], ["بوجهك أولاً لترى الداخل", "بعيداً عن وجهك مع خروج البخار", "بسرعة وانحنِ للداخل"], 1),
    q(M, "Before scraping a mixer bowl you must:", "قبل كشط وعاء الخلاط يجب:",
      ["Slow it down", "Use a longer spatula", "Stop the machine"], ["إبطاؤه", "استعمال ملعقة أطول", "إيقاف الآلة"], 2),
    q(M, "Pan handles on the stove should:", "مقابض القدور على الموقد يجب:",
      ["Not stick out over the edge", "Point outward", "Be removed"], ["ألا تبرز خارج الحافة", "تتجه للخارج", "تُزال"], 0),
    q(H, "Before cooling a burn you should remove:", "قبل تبريد الحرق يجب نزع:",
      ["Nothing", "Rings or tight items near the burn", "The skin"], ["لا شيء", "الخواتم أو ما يضغط قرب الحرق", "الجلد"], 1),
    q(H, "Why not put ice directly on a burn?", "لماذا لا يوضع الثلج مباشرة على الحرق؟",
      ["It melts", "It is expensive", "It can damage the tissue further"], ["يذوب", "مكلف", "قد يزيد تلف الأنسجة"], 2),
    q(H, "How do you lift a 25 kg flour sack?", "كيف ترفع كيس طحين 25 كغ؟",
      ["Bent knees, straight back, close to the body — or use help/a trolley", "Bend at the waist", "Twist while lifting"], ["ثني الركبتين وظهر مستقيم وقريب من الجسم — أو بمساعدة/عربة", "الانحناء من الخصر", "الالتفاف أثناء الرفع"], 0),
    q(H, "A sheeter guard is broken. You:", "حاجز فرادة العجين مكسور. أنت:",
      ["Use it carefully", "Stop using it and report it", "Remove the guard fully"], ["تستعملها بحذر", "توقف استعمالها وتبلغ", "تنزع الحاجز كلياً"], 1),
    q(H, "Oil and syrup spills on the floor must be cleaned:", "انسكاب الزيت والقطر على الأرض يُنظف:",
      ["At closing", "When someone slips", "At once"], ["عند الإغلاق", "عندما ينزلق أحد", "فوراً"], 2),
  ],
};
