// src/pages/sweets-training/content/quizA.js
// Trainee quiz bank, part A (modules 1–7). 5 Easy + 5 Medium + 5 Hard each.
// Shape = the other system's QUIZ_BANK: { difficulty, q_en, q_ar,
// options_en, options_ar, correct } — `correct` is the option index.
const q = (difficulty, q_en, q_ar, options_en, options_ar, correct) =>
  ({ difficulty, q_en, q_ar, options_en, options_ar, correct });
const E = "Easy", M = "Medium", H = "Hard";

export const QUIZ_A = {
  "Personal Hygiene & Handwashing": [
    q(E, "How long should you scrub your hands with soap?", "كم يجب أن تفرك يديك بالصابون؟",
      ["At least 20 seconds", "5 seconds", "Only rinse with water"], ["20 ثانية على الأقل", "5 ثوانٍ", "الشطف بالماء فقط"], 0),
    q(E, "Where must your mobile phone be during production?", "أين يجب أن يكون هاتفك أثناء الإنتاج؟",
      ["In your apron pocket", "In the locker", "On the work table"], ["في جيب المريول", "في الخزانة", "على طاولة العمل"], 1),
    q(E, "What must cover ALL your hair in production?", "ما الذي يجب أن يغطي شعرك كله في الإنتاج؟",
      ["A cap only", "Nothing if hair is short", "A hairnet"], ["قبعة فقط", "لا شيء إذا كان الشعر قصيراً", "شبكة شعر"], 2),
    q(E, "Is hand sanitizer a replacement for handwashing?", "هل معقم اليدين بديل عن غسلهما؟",
      ["No — use it after washing", "Yes, always", "Yes, if hands look clean"], ["لا — يُستعمل بعد الغسل", "نعم دائماً", "نعم إذا بدت اليدان نظيفتين"], 0),
    q(E, "Which is allowed on the hands in production?", "ما المسموح في اليدين أثناء الإنتاج؟",
      ["A watch", "Nail polish", "Short clean nails"], ["ساعة", "طلاء أظافر", "أظافر قصيرة ونظيفة"], 2),
    q(M, "You had diarrhoea last night. What do you do?", "أُصبت بإسهال الليلة الماضية. ماذا تفعل؟",
      ["Work but wash hands more", "Report to the supervisor before starting", "Work only in packing"], ["أعمل وأغسل يدي أكثر", "أبلغ المشرف قبل البدء", "أعمل في التغليف فقط"], 1),
    q(M, "How long after symptoms stop must you stay out of food areas?", "كم تبقى خارج مناطق الغذاء بعد زوال الأعراض؟",
      ["48 hours", "2 hours", "Until the next shift"], ["48 ساعة", "ساعتان", "حتى الوردية التالية"], 0),
    q(M, "What colour plaster is used on a cut?", "ما لون الضماد المستعمل على الجرح؟",
      ["Skin colour", "White", "Blue"], ["لون البشرة", "أبيض", "أزرق"], 2),
    q(M, "When must gloves be changed?", "متى يجب تبديل القفازات؟",
      ["Only at the end of the shift", "When torn, after raw tasks and at least hourly", "Never, if they look clean"], ["فقط في نهاية الوردية", "عند التمزق وبعد المهام النيئة وكل ساعة على الأقل", "أبداً إذا بدت نظيفة"], 1),
    q(M, "Where is the apron taken off?", "أين يُخلع المريول؟",
      ["Before going to the toilet or leaving production", "Only at home", "In the toilet"], ["قبل الذهاب للحمام أو مغادرة الإنتاج", "في البيت فقط", "في الحمام"], 0),
    q(H, "Why is Staphylococcus aureus a special risk in cream and custard?", "لماذا تمثل المكورات العنقودية خطراً خاصاً في الكريمة والكاسترد؟",
      ["It only grows in the freezer", "It comes from hands and noses and makes a toxin baking does not destroy", "It gives a bad smell so it is easy to see"], ["تنمو في الفريزر فقط", "تأتي من الأيدي والأنف وتفرز سماً لا يتلفه الخَبز", "تعطي رائحة كريهة فيسهل كشفها"], 1),
    q(H, "Why are plasters blue?", "لماذا الضمادات زرقاء؟",
      ["Blue is cheaper", "Blue kills bacteria", "Blue is rare in food, so a lost plaster is easy to see"], ["الأزرق أرخص", "الأزرق يقتل البكتيريا", "الأزرق نادر في الطعام فيُرى الضماد إذا سقط"], 2),
    q(H, "Which order is correct?", "أي ترتيب صحيح؟",
      ["Wash → dry with paper → sanitize", "Sanitize → wash → dry", "Wash → sanitize → wipe the sanitizer off"], ["غسل ← تجفيف بمنديل ← تعقيم", "تعقيم ← غسل ← تجفيف", "غسل ← تعقيم ← مسح المعقم"], 0),
    q(H, "After touching raw eggs, before piping cream, you must:", "بعد لمس البيض النيء وقبل تزيين الكريمة يجب أن:",
      ["Wipe hands on the apron", "Wash hands and change gloves", "Only put on more gloves"], ["تمسح يديك بالمريول", "تغسل يديك وتبدّل القفازات", "تلبس قفازاً إضافياً فقط"], 1),
    q(H, "What does every food handler need to hold?", "ماذا يجب أن يحمل كل متداول غذاء؟",
      ["A driving licence", "A bakery diploma", "A valid occupational health card"], ["رخصة قيادة", "شهادة خبّاز", "بطاقة صحة مهنية سارية"], 2),
  ],

  "Allergen Control": [
    q(E, "Does baking destroy allergens?", "هل يتلف الخَبز مسببات الحساسية؟",
      ["No", "Yes", "Only nuts"], ["لا", "نعم", "المكسرات فقط"], 0),
    q(E, "Which of these is a major allergen?", "أي مما يلي مسبب حساسية رئيسي؟",
      ["Sugar", "Tree nuts", "Salt"], ["السكر", "المكسرات", "الملح"], 1),
    q(E, "A customer asks if a cake has nuts and you are not sure. You:", "زبون يسأل إن كان الكيك فيه مكسرات ولست متأكداً. أنت:",
      ["Say no", "Guess from the look", "Say you are not sure and ask the supervisor"], ["تقول لا", "تخمّن من الشكل", "تقول إنك لست متأكداً وتسأل المشرف"], 2),
    q(E, "Where are the allergens of each product listed?", "أين تُسجَّل مسببات الحساسية لكل منتج؟",
      ["In the Allergen Matrix", "Nowhere", "Only in the chef's memory"], ["في مصفوفة مسببات الحساسية", "لا مكان", "في ذاكرة الشيف فقط"], 0),
    q(E, "On which shelf are allergens stored?", "على أي رف تُخزن مسببات الحساسية؟",
      ["The top shelf", "Low shelves, sealed and labelled", "Anywhere"], ["الرف العلوي", "الرفوف السفلى مغلقة ومعنونة", "في أي مكان"], 1),
    q(M, "Which product should be made FIRST in the day?", "أي منتج يُصنع أولاً في اليوم؟",
      ["Pistachio baklava", "Hazelnut praline cake", "A nut-free product"], ["بقلاوة الفستق", "كيك برالين البندق", "منتج خالٍ من المكسرات"], 2),
    q(M, "Soy can be hidden in chocolate as:", "قد يختبئ الصويا في الشوكولاتة على شكل:",
      ["Lecithin", "Cocoa butter", "Vanilla"], ["ليسيثين", "زبدة الكاكاو", "فانيلا"], 0),
    q(M, "A supplier changes the praline paste recipe. What comes first?", "المورد غيّر وصفة عجينة البرالين. ما الذي يأتي أولاً؟",
      ["Nothing — same product name", "Update the Allergen Matrix before production", "Tell customers next month"], ["لا شيء — نفس اسم المنتج", "تحديث مصفوفة الحساسية قبل الإنتاج", "إخبار الزبائن الشهر القادم"], 1),
    q(M, "After a nut product, before a nut-free product you must:", "بعد منتج بالمكسرات وقبل منتج خالٍ منها يجب:",
      ["Wipe the table with a dry cloth", "Change the apron only", "Fully clean equipment and record a visual check"], ["مسح الطاولة بفوطة جافة", "تبديل المريول فقط", "تنظيف المعدات بالكامل وتسجيل فحص بصري"], 2),
    q(M, "Scoops for nuts should be:", "مغارف المكسرات يجب أن تكون:",
      ["Separate and colour-coded", "Shared with flour", "Washed once a week"], ["منفصلة وملونة", "مشتركة مع الطحين", "تُغسل مرة أسبوعياً"], 0),
    q(H, "Which sulphite level must be declared on the label?", "أي مستوى من الكبريتيت يجب ذكره على البطاقة؟",
      ["Any amount above 1000 mg/kg only", "10 mg/kg or more", "Sulphites never need declaring"], ["فقط فوق 1000 ملغ/كغ", "10 ملغ/كغ أو أكثر", "لا يلزم ذكره أبداً"], 1),
    q(H, "Sprinkles used on a cake contain milk. The label:", "الرشّات على الكيك تحتوي حليباً. البطاقة:",
      ["Doesn't need it — decorations don't count", "Only if more than 10% of the cake", "Must declare milk"], ["لا تحتاجه — الزينة لا تُحسب", "فقط إذا تجاوز 10% من الكيك", "يجب أن تذكر الحليب"], 2),
    q(H, "What is 'cross-contact'?", "ما هو 'الانتقال العرضي'؟",
      ["An allergen getting into a product that should not contain it", "Mixing two recipes on purpose", "Touching two trays"], ["دخول مسبب حساسية إلى منتج لا يُفترض أن يحتويه", "خلط وصفتين عمداً", "لمس صينيتين"], 0),
    q(H, "Which document guides allergen management by food businesses?", "أي وثيقة ترشد المنشآت إلى إدارة مسببات الحساسية؟",
      ["GSO 150", "Codex CXC 80-2020", "ISO 9001"], ["GSO 150", "الكودكس CXC 80-2020", "ISO 9001"], 1),
    q(H, "A tray was used for walnut cookies and not washed. It may be used for:", "صينية استُعملت لكوكيز الجوز ولم تُغسل. يمكن استعمالها لـ:",
      ["Nut-free cookies after brushing crumbs", "Any product if lined with paper", "Nothing until washed"], ["كوكيز بلا مكسرات بعد نفض الفتات", "أي منتج إذا فُرش بالورق", "لا شيء حتى تُغسل"], 2),
  ],

  "High-Risk Fillings: Cream, Custard & Cheese": [
    q(E, "At what temperature is fresh cream stored?", "على أي حرارة تُحفظ الكريمة الطازجة؟",
      ["0–5 °C", "10–15 °C", "Room temperature"], ["0–5 °م", "10–15 °م", "حرارة الغرفة"], 0),
    q(E, "What is the maximum temperature of the cream & decoration room?", "ما أعلى حرارة لغرفة الكريمة والتزيين؟",
      ["25 °C", "10 °C", "18 °C"], ["25 °م", "10 °م", "18 °م"], 1),
    q(E, "Leftover cream from the display can be:", "الكريمة المتبقية من العرض يمكن:",
      ["Mixed into tomorrow's batch", "Used for staff cakes", "Not re-used"], ["خلطها مع دفعة الغد", "استعمالها لكيك الموظفين", "لا يُعاد استعمالها"], 2),
    q(E, "Piping bags should be:", "أكياس التزيين يجب أن تكون:",
      ["Clean and sanitised, single-use preferred", "Washed weekly", "Shared between cream and raw egg"], ["نظيفة ومعقمة ويُفضل ذات الاستعمال الواحد", "تُغسل أسبوعياً", "مشتركة بين الكريمة والبيض النيء"], 0),
    q(E, "Every filled product carries:", "كل منتج محشو يحمل:",
      ["Only the price", "Production date and use-by", "Nothing"], ["السعر فقط", "تاريخ الإنتاج وتاريخ الاستعمال", "لا شيء"], 1),
    q(M, "A cream cake has been above 5 °C for 3 hours. You:", "كيك كريمة بقي فوق 5 °م لمدة 3 ساعات. أنت:",
      ["Put it back in the chiller", "Sell it at a discount", "Discard it"], ["تعيده للبراد", "تبيعه بخصم", "تتلفه"], 2),
    q(M, "Custard must reach a core temperature of at least:", "يجب أن يصل قلب الكاسترد إلى حرارة لا تقل عن:",
      ["75 °C", "50 °C", "63 °C only at the surface"], ["75 °م", "50 °م", "63 °م على السطح فقط"], 0),
    q(M, "Which eggs are used in a mousse that is not cooked?", "أي بيض يُستعمل في موس لا يُطبخ؟",
      ["Any fresh eggs", "Pasteurised eggs", "Cracked eggs are fine"], ["أي بيض طازج", "بيض مبستر", "البيض المكسور مقبول"], 1),
    q(M, "Why take out only the cream you will use now?", "لماذا تُخرج فقط الكريمة التي ستستعملها الآن؟",
      ["To save space", "Because it melts the chocolate", "To limit time above 5 °C"], ["لتوفير المساحة", "لأنها تذيب الشوكولاتة", "لتقليل الوقت فوق 5 °م"], 2),
    q(M, "Which bacterium is linked to raw eggs?", "أي بكتيريا ترتبط بالبيض النيء؟",
      ["Salmonella", "Lactobacillus", "Yeast"], ["السالمونيلا", "اللاكتوباسيلس", "الخميرة"], 0),
    q(H, "Cooked custard at 60 °C must reach 21 °C within:", "الكاسترد المطبوخ على 60 °م يجب أن يصل 21 °م خلال:",
      ["12 hours", "2 hours", "30 minutes exactly"], ["12 ساعة", "ساعتين", "30 دقيقة بالضبط"], 1),
    q(H, "Why are fillings high-risk?", "لماذا الحشوات عالية الخطورة؟",
      ["They are sweet", "They are cooked twice", "Moist, protein-rich, often not cooked after assembly"], ["لأنها حلوة", "لأنها تُطبخ مرتين", "رطبة وغنية بالبروتين ولا تُطبخ غالباً بعد التجميع"], 2),
    q(H, "Listeria is a particular risk in:", "الليستيريا خطر خاص في:",
      ["Chilled dairy products", "Sugar syrup", "Dry biscuits"], ["منتجات الألبان المبردة", "القطر السكري", "البسكويت الجاف"], 0),
    q(H, "You top up a half-used bowl of cream with fresh cream. The problem is:", "أضفت كريمة طازجة إلى وعاء نصف مستعمل. المشكلة:",
      ["None", "The old cream contaminates the new and its age is lost", "Only the colour changes"], ["لا مشكلة", "القديمة تلوث الجديدة ويضيع عمرها", "يتغير اللون فقط"], 1),
    q(H, "Total cooling time for a filling to reach ≤ 5 °C is:", "الوقت الإجمالي لتبريد الحشوة حتى 5 °م أو أقل:",
      ["24 hours", "1 hour", "6 hours"], ["24 ساعة", "ساعة واحدة", "6 ساعات"], 2),
  ],

  "Baking, Cooking & Sugar Syrups": [
    q(E, "What proves that custard is cooked?", "ما الذي يثبت أن الكاسترد مطبوخ؟",
      ["A probe reading of ≥ 75 °C in the core", "Its colour", "The cooking time on the clock"], ["قراءة المجس 75 °م أو أكثر في القلب", "لونه", "وقت الطبخ على الساعة"], 0),
    q(E, "When is the probe thermometer cleaned?", "متى يُنظف ميزان الحرارة؟",
      ["Once a week", "Before and after every use", "Never"], ["مرة أسبوعياً", "قبل وبعد كل استعمال", "أبداً"], 1),
    q(E, "Where do you insert the probe?", "أين تُدخل المجس؟",
      ["On the surface", "In the pan edge", "In the centre / thickest part"], ["على السطح", "في حافة القدر", "في المركز / أسمك جزء"], 2),
    q(E, "Under-baked product with a raw centre is:", "المنتج غير المكتمل بقلب نيء:",
      ["Re-baked or rejected", "Sold as soft-centre", "Frozen and sold later"], ["يُعاد خبزه أو يُرفض", "يُباع كقلب طري", "يُجمد ويُباع لاحقاً"], 0),
    q(E, "Syrup should be kept:", "القطر يجب أن يُحفظ:",
      ["Open with a spoon inside", "Covered and clean", "On the floor to cool"], ["مكشوفاً وفيه ملعقة", "مغطى ونظيفاً", "على الأرض ليبرد"], 1),
    q(M, "How often are thermometers checked in ice and boiling water?", "كم مرة تُفحص الموازين في الماء المثلج والمغلي؟",
      ["Every year", "Never", "Monthly"], ["كل سنة", "أبداً", "شهرياً"], 2),
    q(M, "In ice water, a thermometer should read:", "في الماء المثلج يجب أن يقرأ الميزان:",
      ["0 °C (± 1 °C)", "10 °C", "−18 °C"], ["0 °م (± 1 °م)", "10 °م", "−18 °م"], 0),
    q(M, "Frying oil must be changed when it is:", "زيت القلي يُبدّل عندما:",
      ["Still light", "Dark, foaming or smoking", "Used once"], ["يكون فاتحاً", "يغمق أو يرغي أو يدخّن", "يُستعمل مرة واحدة"], 1),
    q(M, "What is recorded for each oven batch?", "ماذا يُسجَّل لكل دفعة فرن؟",
      ["Only the baker's name", "Nothing", "Set temperature, start and end"], ["اسم الخبّاز فقط", "لا شيء", "الحرارة المضبوطة ووقت البدء والانتهاء"], 2),
    q(M, "After cooking, a filling is either cooled fast or held at:", "بعد الطبخ إما تُبرّد الحشوة بسرعة أو تُحفظ على:",
      ["≥ 60 °C", "30 °C", "Room temperature"], ["60 °م أو أكثر", "30 °م", "حرارة الغرفة"], 0),
    q(H, "Why is adding fresh oil on top of old oil wrong?", "لماذا إضافة زيت جديد فوق القديم خطأ؟",
      ["It is expensive", "Degraded oil stays in use and keeps breaking down", "It makes the oil too cold forever"], ["لأنه مكلف", "يبقى الزيت المتحلل مستعملاً ويستمر تحلله", "يجعل الزيت بارداً للأبد"], 1),
    q(H, "A thermometer reads 97 °C in boiling water at sea level. It is:", "ميزان يقرأ 97 °م في ماء مغلي عند سطح البحر. هو:",
      ["Accurate", "Within ± 1 °C", "Out of tolerance — take it out of use"], ["دقيق", "ضمن ± 1 °م", "خارج السماحية — يُسحب من الاستعمال"], 2),
    q(H, "Why is surface colour not proof of cooking?", "لماذا لا يثبت لون السطح النضج؟",
      ["The core can still be below a safe temperature", "Colour changes with the oven brand", "Colour is only for chocolate"], ["قد يبقى القلب تحت الحرارة الآمنة", "اللون يتغير حسب نوع الفرن", "اللون للشوكولاتة فقط"], 0),
    q(H, "A cooked filling missed its cooling stage 1. The right action:", "حشوة مطبوخة فشلت في المرحلة 1 من التبريد. الإجراء الصحيح:",
      ["Put it in the freezer and forget it", "Re-heat once to ≥ 75 °C and restart, or discard", "Add sugar"], ["ضعها في الفريزر وانسَها", "أعد تسخينها مرة إلى 75 °م وابدأ من جديد أو أتلفها", "أضف السكر"], 1),
    q(H, "What is the danger zone?", "ما هي منطقة الخطر؟",
      ["−18 to 0 °C", "75 to 100 °C", "5 to 60 °C"], ["−18 إلى 0 °م", "75 إلى 100 °م", "5 إلى 60 °م"], 2),
  ],

  "Cooling, Chilled Storage & Display": [
    q(E, "The chiller temperature range is:", "مدى حرارة البراد:",
      ["0–5 °C", "6–10 °C", "−5 to 0 °C"], ["0–5 °م", "6–10 °م", "−5 إلى 0 °م"], 0),
    q(E, "The freezer must be at:", "يجب أن يكون الفريزر على:",
      ["−5 °C", "−18 °C or colder", "0 °C"], ["−5 °م", "−18 °م أو أبرد", "0 °م"], 1),
    q(E, "Ready-to-eat products are stored:", "المنتجات الجاهزة للأكل تُخزن:",
      ["Below raw materials", "On the floor", "Above raw materials"], ["تحت المواد الخام", "على الأرض", "فوق المواد الخام"], 2),
    q(E, "Everything in the chiller must be:", "كل ما في البراد يجب أن يكون:",
      ["Covered, labelled and dated", "Uncovered to cool", "In the original box only"], ["مغطى ومعنوناً ومؤرخاً", "مكشوفاً ليبرد", "في الكرتونة الأصلية فقط"], 0),
    q(E, "Chilled display must be at:", "العرض المبرّد يجب أن يكون على:",
      ["10 °C", "≤ 5 °C", "Room temperature"], ["10 °م", "5 °م أو أقل", "حرارة الغرفة"], 1),
    q(M, "How often are chillers checked?", "كم مرة تُفحص البرادات؟",
      ["Once a week", "Only when broken", "Every 2 hours (4 AM – 8 PM)"], ["مرة أسبوعياً", "عند العطل فقط", "كل ساعتين (4 ص – 8 م)"], 2),
    q(M, "Cooling stage 1 is:", "المرحلة 1 من التبريد هي:",
      ["60 → 21 °C within 2 hours", "60 → 5 °C within 30 minutes", "21 → 5 °C within 24 hours"], ["من 60 إلى 21 °م خلال ساعتين", "من 60 إلى 5 °م خلال 30 دقيقة", "من 21 إلى 5 °م خلال 24 ساعة"], 0),
    q(M, "Which helps cooling most?", "ما الذي يساعد التبريد أكثر؟",
      ["A large deep pot on the bench", "Shallow trays and an ice bath or blast chiller", "Covering it with a towel"], ["قدر كبير عميق على الطاولة", "صوانٍ ضحلة وحمام ثلج أو مبرد سريع", "تغطيته بمنشفة"], 1),
    q(M, "The chiller reads 8 °C. First you:", "البراد يقرأ 8 °م. أولاً أنت:",
      ["Ignore it until tomorrow", "Turn it off", "Probe the products and move them to another chiller"], ["تتجاهله للغد", "تطفئه", "تقيس حرارة المنتجات وتنقلها لبراد آخر"], 2),
    q(M, "How many product probe checks are made per day at least?", "كم فحص حرارة منتج يومياً على الأقل؟",
      ["2", "0", "1 per week"], ["2", "0", "1 أسبوعياً"], 0),
    q(H, "At which freezer reading is it CRITICAL?", "عند أي قراءة يصبح الفريزر حرجاً؟",
      ["−20 °C", "Above −15 °C", "−18 °C"], ["−20 °م", "أعلى من −15 °م", "−18 °م"], 1),
    q(H, "Why must display units not be overloaded?", "لماذا لا تُحمَّل وحدات العرض فوق طاقتها؟",
      ["It looks untidy", "Customers can't choose", "Cold air can't circulate, so products warm up"], ["شكلها غير مرتب", "الزبون لا يستطيع الاختيار", "لا يدور الهواء البارد فتسخن المنتجات"], 2),
    q(H, "Cooling stage 2 means reaching ≤ 5 °C within:", "المرحلة 2 تعني الوصول إلى 5 °م أو أقل خلال:",
      ["6 hours in total", "2 more days", "15 minutes"], ["6 ساعات إجمالاً", "يومين إضافيين", "15 دقيقة"], 0),
    q(H, "Why is cooling in two stages?", "لماذا التبريد على مرحلتين؟",
      ["It saves electricity", "The fastest growth is between 60 and 21 °C, so that part must be quickest", "Chillers work only in stages"], ["يوفر الكهرباء", "أسرع نمو بين 60 و21 °م فيجب أن يكون هذا الجزء الأسرع", "البرادات تعمل على مراحل فقط"], 1),
    q(H, "A cream product has been in display at 7 °C for 3 hours. It is:", "منتج كريمة في العرض على 7 °م لمدة 3 ساعات. هو:",
      ["Moved to a colder shelf and sold", "Sold today only", "Discarded"], ["يُنقل لرف أبرد ويُباع", "يُباع اليوم فقط", "يُتلف"], 2),
  ],

  "Thawing (Defrosting)": [
    q(E, "The preferred thawing method is:", "طريقة الإذابة المفضلة:",
      ["In the chiller", "On the bench", "In hot water"], ["في البراد", "على الطاولة", "في ماء ساخن"], 0),
    q(E, "Can a thawed item be refrozen?", "هل يُعاد تجميد الصنف المذاب؟",
      ["Yes, once", "No, never", "Yes, if it still looks good"], ["نعم مرة واحدة", "لا أبداً", "نعم إذا بدا جيداً"], 1),
    q(E, "In cold running water the water must be:", "في الماء البارد الجاري يجب أن يكون الماء:",
      ["Hot", "Any temperature", "≤ 21 °C"], ["ساخناً", "أي حرارة", "21 °م أو أقل"], 2),
    q(E, "In water, the product must be:", "في الماء يجب أن يكون المنتج:",
      ["Sealed", "Unwrapped", "Cut into pieces"], ["مغلقاً", "مكشوفاً", "مقطعاً"], 0),
    q(E, "What is recorded when thawing starts?", "ماذا يُسجَّل عند بدء الإذابة؟",
      ["Nothing", "Method, date, time and temperature", "Only the item name"], ["لا شيء", "الطريقة والتاريخ والوقت والحرارة", "اسم الصنف فقط"], 1),
    q(M, "The maximum time in cold running water is:", "أقصى وقت في الماء البارد الجاري:",
      ["12 hours", "Overnight", "4 hours"], ["12 ساعة", "طوال الليل", "4 ساعات"], 2),
    q(M, "At the end of chiller thawing, the item core must be:", "عند انتهاء الإذابة في البراد يجب أن يكون لب الصنف:",
      ["≤ 5 °C", "≥ 21 °C", "Still frozen in the middle is fine"], ["5 °م أو أقل", "21 °م أو أكثر", "بقاء الوسط مجمداً مقبول"], 0),
    q(M, "Which may be thawed at room temperature?", "أي صنف يمكن إذابته على حرارة الغرفة؟",
      ["Frozen cream", "Plain dough (low risk)", "Custard"], ["الكريمة المجمدة", "العجين السادة (منخفض الخطورة)", "الكاسترد"], 1),
    q(M, "Use-by after thawing for dairy, egg, cheese and fillings is:", "صلاحية الاستعمال بعد الإذابة للألبان والبيض والجبن والحشوات:",
      ["7 days", "72 hours", "24 hours"], ["7 أيام", "72 ساعة", "24 ساعة"], 2),
    q(M, "Use-by after thawing for butter, dough and fruit is:", "صلاحية الاستعمال بعد الإذابة للزبدة والعجين والفاكهة:",
      ["72 hours", "24 hours", "2 weeks"], ["72 ساعة", "24 ساعة", "أسبوعان"], 0),
    q(H, "Why is thawing cream on the bench dangerous?", "لماذا إذابة الكريمة على الطاولة خطرة؟",
      ["It gets too cold", "The surface sits in the danger zone while the centre is still frozen", "It changes flavour only"], ["تصبح باردة جداً", "يبقى السطح في منطقة الخطر بينما الوسط مجمد", "يتغير الطعم فقط"], 1),
    q(H, "The thawing sheet shows a banner of thaws from yesterday. It means:", "ورقة الإذابة تُظهر تنبيهاً لإذابات من الأمس. هذا يعني:",
      ["A system error", "Nothing important", "Those thaws were not closed — record their end and use-by"], ["خطأ في النظام", "لا شيء مهم", "تلك الإذابات لم تُغلق — سجّل انتهاءها وصلاحيتها"], 2),
    q(H, "Where does the frozen lot number for a thaw come from?", "من أين يأتي رقم الدفعة المجمدة للإذابة؟",
      ["From the raw material receiving record", "Invented by the worker", "From the price list"], ["من سجل استلام المواد الخام", "يخترعه العامل", "من قائمة الأسعار"], 0),
    q(H, "A thaw in water reached 5 hours. You:", "إذابة في الماء بلغت 5 ساعات. أنت:",
      ["Continue until soft", "Treat it as out of limit: tell the supervisor, who decides and records", "Refreeze it"], ["تستمر حتى تلين", "تعاملها كخارج الحد: تبلغ المشرف الذي يقرر ويسجل", "تعيد تجميدها"], 1),
    q(H, "Why thaw only what you will use?", "لماذا تذيب فقط ما ستستعمله؟",
      ["It is faster", "The chiller gets too cold", "Thawed stock cannot be refrozen and its use-by is short"], ["أسرع", "البراد يبرد كثيراً", "المخزون المذاب لا يُعاد تجميده وصلاحيته قصيرة"], 2),
  ],

  "Receiving & Dry Store": [
    q(E, "Chilled deliveries (cream, milk, eggs) must arrive at:", "الشحنات المبردة (كريمة، حليب، بيض) يجب أن تصل على:",
      ["≤ 5 °C", "≤ 15 °C", "Any temperature"], ["5 °م أو أقل", "15 °م أو أقل", "أي حرارة"], 0),
    q(E, "Frozen deliveries must arrive at:", "الشحنات المجمدة يجب أن تصل على:",
      ["−5 °C", "≤ −18 °C with no signs of thawing", "0 °C"], ["−5 °م", "−18 °م أو أقل بلا علامات ذوبان", "0 °م"], 1),
    q(E, "FEFO means:", "FEFO تعني:",
      ["First Everything, First Out", "Freshest Eaten First", "First Expired, First Out"], ["كل شيء أولاً", "الأطزج يُؤكل أولاً", "الأقرب انتهاءً يخرج أولاً"], 2),
    q(E, "Goods in the dry store are kept:", "البضائع في المخزن الجاف تُحفظ:",
      ["On shelves off the floor", "On the floor near the wall", "Outside"], ["على رفوف مرتفعة عن الأرض", "على الأرض قرب الجدار", "في الخارج"], 0),
    q(E, "A pack arrives torn with signs of insects. You:", "وصلت عبوة ممزقة وفيها آثار حشرات. أنت:",
      ["Accept and use first", "Reject it", "Tape it closed"], ["تقبلها وتستعملها أولاً", "ترفضها", "تغلقها بشريط لاصق"], 1),
    q(M, "Chilled items go into the chiller within:", "المواد المبردة تدخل البراد خلال:",
      ["2 hours", "The end of the shift", "15 minutes"], ["ساعتين", "نهاية الوردية", "15 دقيقة"], 2),
    q(M, "What must nuts come with from the supplier?", "ماذا يجب أن يرافق المكسرات من المورد؟",
      ["A certificate of analysis (aflatoxin)", "A gift", "Nothing"], ["شهادة تحليل (أفلاتوكسين)", "هدية", "لا شيء"], 0),
    q(M, "Why record the lot number of each delivery?", "لماذا يُسجَّل رقم دفعة كل شحنة؟",
      ["For decoration", "So a recall can trace it", "It is not needed"], ["للزينة", "حتى يمكن تتبعه عند السحب", "غير مطلوب"], 1),
    q(M, "Opened flour and sugar are kept:", "الطحين والسكر المفتوحان يُحفظان:",
      ["In the open sack", "On the bench", "In closed, labelled containers"], ["في الكيس المفتوح", "على الطاولة", "في حاويات مغلقة ومعنونة"], 2),
    q(M, "Which is checked on the delivery vehicle?", "ما الذي يُفحص في سيارة التوصيل؟",
      ["Clean and cold", "Its colour", "The driver's shoes"], ["نظيفة ومبردة", "لونها", "حذاء السائق"], 0),
    q(H, "Aflatoxin is a hazard of type:", "الأفلاتوكسين خطر من النوع:",
      ["Physical", "Chemical (mould toxin)", "Biological (virus)"], ["فيزيائي", "كيميائي (سم فطري)", "حيوي (فيروس)"], 1),
    q(H, "Frozen butter arrives at −12 °C and soft at the edges. You:", "زبدة مجمدة وصلت على −12 °م وطرية عند الأطراف. أنت:",
      ["Accept and refreeze it", "Accept for immediate use", "Reject it"], ["تقبلها وتعيد تجميدها", "تقبلها للاستعمال الفوري", "ترفضها"], 2),
    q(H, "Which delivery lot should be used first?", "أي دفعة تُستعمل أولاً؟",
      ["The one with the nearest expiry", "The newest delivery", "The biggest box"], ["الأقرب انتهاءً", "الأحدث وصولاً", "الكرتونة الأكبر"], 0),
    q(H, "Which Codex code covers aflatoxin in tree nuts?", "أي مدونة كودكس تخص الأفلاتوكسين في المكسرات؟",
      ["CXC 80-2020", "CXC 59-2005", "GSO 9"], ["CXC 80-2020", "CXC 59-2005", "GSO 9"], 1),
    q(H, "Why are allergens stored on low shelves?", "لماذا تُخزن مسببات الحساسية على الرفوف السفلى؟",
      ["They are heavy", "They are used least", "So spills cannot fall onto other products"], ["لأنها ثقيلة", "لأنها الأقل استعمالاً", "حتى لا يسقط انسكابها على منتجات أخرى"], 2),
  ],
};
